### ISSUE TITLE
[EPIC] Can CNF run in a zero trust network.

### ISSUE THREAD

**Issue by wavell** [cnti-testcatalog/testsuite#1005]
**Is your feature request related to a problem? Please describe.**

Some CNF s might fail if running in a zero trust network

What is a Zero Trust Network?

A zero trust network is built upon five fundamental assertions:

1) The network is always assumed to be hostile.
2) External and internal threats exist on the network at all times.
3) Network locality is not sufficient for deciding trust in a network.
4) Every device, user, and network flow is authenticated and authorized.
5) Policies must be dynamic and calculated from as many sources of data as possible.

![1633377654784](https://user-images.githubusercontent.com/29548/135916744-4f492191-e52c-4819-b69f-a2045865a6aa.jpg)
![IMG_20211004_145352__01](https://user-images.githubusercontent.com/29548/135917029-ca97bb83-9c88-44c6-b77a-a38c4af93f73.jpg)

**Describe the solution you'd like**
The test suite should check if the CNF runs in a zero trust network

**Comment by lixuna** [comment]
closing issue as stale - can be reopened if prioritized by community
