### ISSUE TITLE
[Platform] Check `Exec into container` permissions for kubectl exec

### ISSUE THREAD

**Issue by agentpoyo** [cnti-testcatalog/testsuite#1046]
### CATEGORY_NAME test: Exec into Container

**Short description of platform test:**
- Attackers who have permissions, can run malicious commands in containers in the cluster using exec command (“kubectl exec”). In this method, attackers can use legitimate images, such as an OS image (e.g., Ubuntu) as a backdoor container, and run their malicious code remotely by using “kubectl exec”.

- Check which subjects have RBAC permissions to exec into pods– if they have the “pods/exec” verb.

**Remediation Details**

- It is recommended to prohibit “kubectl exec” command in production environments. It is also recommended not to use subjects with this permission for daily cluster operations. 
- You should apply least privilege principal (we can point to our audit/least privilege screen). You should monitor and approve users who can exec into containers.

**Test Category**

- Platform:Security 

**References**

- #963 
- https://hub.armo.cloud/docs/c-0002#exec-into-container

---

### Implementation Tasks: TBD

**Environment set up tasks:**

- [ ]

**Upstream tool set up tasks: (test suite + upstream tools)**

- [ ] kubescape

**CNF setup Tasks**

- [ ] `./cnf-testsuite exec_container`

**Sample CNF tasks:**

- [ ]

**Code implementation tasks:**

- [ ]

**Documentation tasks:**

- [ ] Update [Test Categories md](https://github.com/cncf/cnf-testsuite/blob/main/TEST-CATEGORIES.md) if needed
- [ ] Update [Pseudo Code md](https://github.com/cncf/cnf-testsuite/blob/main/PSEUDO-CODE.md) if needed
- [ ] Update [USAGE md](https://github.com/cncf/cnf-testsuite/blob/main/USAGE.md) if needed
  - [ ] Add description details to USAGE md
  - [ ] Add remediation details to USAGE md
- [ ] Update [installation instructions](https://github.com/cncf/cnf-testsuite/install.md) if needed

### QA tasks

Dev Review:

- [ ] walk through A/C
- [ ] do you get the expected result?
- [ ] if yes,
  - [ ] move to `Needs Peer Review` column
  - [ ] create Pull Request and follow check list
  - [ ] Assign 1 or more people for peer review
- [ ] if no, document what additional tasks will be needed

Peer review:

- [ ] walk through A/C
- [ ] do you get the expected result?
- [ ] if yes,
  - [ ] move to `Reviewer Approved` column
  - [ ] Approve pull request
- [ ] if no,
  - [ ] document what did not go as expected, including error messages and screenshots (if possible)
  - [ ] Add comment to pull request
  - [ ] request changes to pull request

**Comment by lixuna** [comment]
@agentpoyo  is this issue still relevant for CNTI?
