### ISSUE TITLE
[Workload] Pods Per Node Scalability Test

### ISSUE THREAD

**Issue by agentpoyo** [cnti-testcatalog/testsuite#1071]
## Title: [Workload] Scalability test: Pods Per Node

**Describe the solution you'd like**
- Kubernetes v1.22 can now handle up to 5000 nodes per cluster but best practice dictates there should be no more than 110 pods per node for your CNF.
- https://kubernetes.io/docs/setup/best-practices/cluster-large/

**Test Category Name**
- Scalability

---

### Documentation tasks:
- [ ] Update [installation instructions](https://github.com/cncf/cnf-testsuite/blob/main/install.md) if needed
- [ ] Update [Test Categories md](https://github.com/cncf/cnf-testsuite/blob/main/TEST-CATEGORIES.md) if needed
- [ ] Update [USAGE md](https://github.com/cncf/cnf-testsuite/blob/main/USAGE.md) if needed
  - [ ] How to run
  - [ ] Description and details
    - [ ] What the best practice is
    - [ ] Why are we testing this
  - [ ] Remediation steps if test does not pass

### QA tasks

Dev Review:

- [ ] walk through A/C
- [ ] do you get the expected result?
- [ ] if yes,
  - [ ] move to `Needs Peer Review` column
  - [ ] create Pull Request and follow check list
  - [ ] Assign 1 or more people for peer review
- [ ] if no, document what additional tasks will be needed

Peer review:

- [ ] walk through A/C
- [ ] do you get the expected result?
- [ ] if yes,
  - [ ] move to `Reviewer Approved` column
  - [ ] Approve pull request
- [ ] if no,
  - [ ] document what did not go as expected, including error messages and screenshots (if possible)
  - [ ] Add comment to pull request
  - [ ] request changes to pull request

**Comment by lixuna** [comment]
@agentpoyo  is this issue still relevant for CNTI?
