### ISSUE TITLE
[BUG] Negative tests for kubescape

### ISSUE THREAD

**Issue by wavell** [cnti-testcatalog/testsuite#1122]
**Describe the bug**
We need three more negative tests for kubescape

**To Reproduce**

**Expected behavior**
The following specs should pass by using negative tests to check if kubescape fails

 1) Security 'insecure_capabilities' should fail on a cnf that has containers with insecure capabilities
     Failure/Error: (/PASSED: Containers with insecure capabilities were not found/ =~ response_s).should be_nil

       Expected: 2202 to be nil

     # spec/workload/security_spec.cr:116

  2) Security 'dangerous_capabilities' should fail on a cnf that has containers with dangerous capabilities
     Failure/Error: (/PASSED: Containers with dangerous capabilities were not found/ =~ response_s).should be_nil

       Expected: 2202 to be nil

     # spec/workload/security_spec.cr:142

  3) Security 'application_credentials' should fail on a cnf that allows applications credentials in configuration files
     Failure/Error: (/FAILED: Found applications credentials in configuration files/ =~ response_s).should_not be_nil

       Expected: nil not to be nil

     # spec/workload/security_spec.cr:168

**Comment by lixuna** [comment]
@wavell @taylor is this issue still relevant for cnti?
