### ISSUE TITLE
[BUG] Duplicate FAILED output when running `workload` or `resilience` tests using Microk8s and kind

### ISSUE THREAD

**Issue by agentpoyo** [cnti-testcatalog/testsuite#1131]
**Describe the bug**
When running `workload` tests, the `resilience` litmus tests that fail display plain text of the failure before the red text output to indicate if the test failed.

**To Reproduce**

1. Setup Microk8s v1.21
2. Setup the sample_coredns CNF from our repository samples
3. Run `workload` or `resilience`
4. You should see duplicate output for FAIL tests, one that's plain text and the other in Red font with X and emoji output.

**Expected behavior**
When tests fail, they should output the standard error in RED text with the red X and message, not in plain white terminal text. See Screenshot below:

**Screenshots**
![bug_1013_resilience_output_mk8s](https://user-images.githubusercontent.com/14348948/145278122-61246012-1e67-47d8-8bcd-342e8bd69e0d.jpg)

**Device (please complete the following information):**

- OS - Linux
- Distro - Debian
- Version - 11
- Architecture - x86
- k8s platform - Microk8s v1.21

**Comment by agentpoyo** [comment]
This is in relation to #1013

**Comment by agentpoyo** [comment]
Reproduced these duplicate white text errors using a single kind node setup as well:

![1131_kind_duplicate_errors](https://user-images.githubusercontent.com/14348948/146248263-63905e89-9bbb-406b-bab8-9c075de2e622.png)

**Comment by lixuna** [comment]
@agentpoyo can this issue be closed?
