### ISSUE TITLE
[Feature] Split out the Airgap from cnf-testsuite `main` code and repository

### ISSUE THREAD

**Issue by agentpoyo** [cnti-testcatalog/testsuite#1160]
**Is your feature request related to a problem? Please describe.**
The airgap code needs to be split out from the rest of cnf-testsuite. There is already a module, separating the entire airgap code from the main code will fix long running CI workflows.

**Describe the solution you'd like**
Split the airgap code from the cnf-testsuite main code and perhaps put it within it's own repository.

The airgap binary tests are taking over an hour to run on every commit and push to cnf-testsuite repository which will relieve development time when debugging and verifying CI workflows in github actions.

**Comment by lixuna** [comment]
This issue is still relevant - Test Catalog group is discussing if airgapped support should be removed for CNTI test catalog

**Comment by kosstennbl** [comment]
Airgap mode support was completely removed from testsuite.
