### ISSUE TITLE
[BUG] Fix Wait Count for the Jaeger Tracing Test.

### ISSUE THREAD

**Issue by denverwilliams** [cnti-testcatalog/testsuite#1163]
**Describe the bug**
New Jaeger clients can sometimes take a long time to register. A temporarily work-around was added by hard-coding a longer timeout (https://github.com/cncf/cnf-testsuite/blob/main/src/tasks/utils/cnf_manager.cr#L891), but this is excessive and new clients normally register in less than 10 seconds. This should be cleaned up so it only waits until a new client is registered and timeout if a new client isn't seen within 5 minutes.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device (please complete the following information):**

- OS [e.g. Linux, iOS, Windows, Android]
- Distro [e.g. Ubuntu]
- Version [e.g. 18.04]
- Architecture [e.g. x86, arm]

**How will this be tested? aka Acceptance Criteria (optional)**

(optional: unnecessary for things like spelling errors and such)

Once this issue is address how will the fix be verified?

**Additional context**

---

NOTE: you can enable higher logging level output via the command line or env var. to help with debugging

```
# cmd line
./cnf-testsuite -l debug test

# make sure to use -- if running from source
crystal src/cnf-testsuite.cr -- -l debug test

# env var
LOGLEVEL=DEBUG ./cnf-testsuite test
```

Also setting the verbose option for many tasks will add extra output to help with debugging

```
crystal src/cnf-testsuite.cr test_name verbose
```

Check [usage documentation](https://github.com/cncf/cnf-testsuite/blob/main/USAGE.md) for more info about invoking commands and logging

**Comment by lixuna** [comment]
@taylor is this issue still relevant for CNTI?
