### ISSUE TITLE
[BUG] Compatibility category has 11 tests but outputs 12 test statuses

### ISSUE THREAD

**Issue by HashNuke** [cnti-testcatalog/testsuite#1197]
## Describe the bug

The following are the tests in the compatibility category.

1. install_script_helm
2. helm_chart_valid
3. helm_chart_published
4. helm_deploy
5. cni_compatible
6. increase_capacity
7. decrease_capacity
8. rollback
9. rolling_update
10. rolling_downgrade
11. rolling_version_change

## Test output for compatibility category

* Test output has 12 lines of test statuses.
* The rollback test has two simultaneous test outputs. One for failure and one for success.
* Line-128 prints a failure message but there is no exit after that and the test continues to output a success message.

### Test output for rollback test
```
✖️  FAILED: please specify a different version than the helm chart default image.tag for 'rollback_from_tag'
✔️  PASSED: CNF Rollback Passed
```

### compatibility category test output

![image](https://user-images.githubusercontent.com/84005/152114773-7c6eb1b7-8b81-4fa7-9e48-51972b4e299d.png)

## To Reproduce

To reproduce, run the compatibility test category in the main branch.

```
./cnf-testsuite compatibility
```

## Expected behaviour

Test output for rollback should be only one status instead of two.

**Comment by HashNuke** [comment]
Based on the conditions in `compatibility.cr`.
* It looks like version change is being applied for rollback even though `version_change_applied` is set to false earlier in the code due to other failures.
* Probably best to separate the variables that decide whether version change is to be applied and the variable where the result is stored after applying the version change.

![image](https://user-images.githubusercontent.com/84005/152116142-6c83ce0e-a85d-4ef4-ae96-bf7fd56beb98.png)

**Comment by lixuna** [comment]
hi @HashNuke is still issue still relevant for cnti?
