### ISSUE TITLE
[BUG] privileged and privileged_containers tests have very similar pass messages

### ISSUE THREAD

**Issue by HashNuke** [cnti-testcatalog/testsuite#1200]
## Describe the bug
`privileged` and `privileged_containers` tests have very similar pass messages. Making it harder to identify what was tested.

`privileged` test has the following pass message
```
PASSED: No privileged containers
```

`privileged_containers` test has the following pass message
```
PASSED: No privileged containers were found
```

When the workload tests are run, the output looks like below.
![CleanShot 2022-02-03 at 15 08 36@2x](https://user-images.githubusercontent.com/84005/152317613-a2939d0a-cb43-40b3-b371-aaa9d360a1c8.png)

## To Reproduce

```
./cnf-testsuite privileged
./cnf-testsuite privileged_containers
```

## Expected behaviour

* A different/clearer/concise message that mentions that was tested for in each of these pass messages.
* OR if these two tests overlap then one of these tests should be removed.

**Comment by taylor** [comment]
@HashNuke @denverwilliams @agentpoyo are these duplicate tests?

**Comment by lixuna** [comment]
The description in the code is the same for these two tests as well

See:
https://github.com/cncf/cnf-testsuite/blob/v0.27.0/src/tasks/workload/security.cr#L125
> desc "Check if any containers are running in privileged mode"
> task "privileged" do |_, args|

And:
https://github.com/cncf/cnf-testsuite/blob/v0.27.0/src/tasks/workload/security.cr#L156
> desc "Check if any containers are running in privileged mode"
> task "privilege_escalation", ["kubescape_scan"] do |_, args|

**Comment by agentpoyo** [comment]
Yes, I believe they are performing the same basic check of whether the containers are in privileged mode or not, we should pick one and remove one. @taylor

**Comment by kosstennbl** [comment]
This duplicity in tests was removed by #2119.
