### ISSUE TITLE
[BUG] database_persistence and elastic_volumes test have very similar success and failure messages

### ISSUE THREAD

**Issue by HashNuke** [cnti-testcatalog/testsuite#1201]
## Describe the bug

`database_persistence` and `elastic_volumes` test have very similar success and failure messages. When reading the testsuite output, it is hard to understand what was tested for.

Below is an example workload run with failure messages for both test outputs.

![image](https://user-images.githubusercontent.com/84005/152320263-cc302617-09ed-428b-82dc-397a5d409616.png)

### Messages for the `database_persistence` test

```
PASSED: Elastic Volumes Used
PASSED: Elastic Volumes and Statefulsets Used
FAILED: Elastic Volumes Not Used
FAILED: Statefulset used without an elastic volume
```

### Messages for the `elastic_volumes` test

```
PASSED: Elastic Volumes Used
FAILED: Elastic Volumes Not Used
```

## To Reproduce

Try running the `elastic_volumes` test and the `database_persistence` tests as a part of the workload group.

```
./cnf-testsuite workload
```

## Expected behavior

Indicate what is being tested in the appropriate success/failure messages.

**Comment by kosstennbl** [comment]
Should be closed because https://github.com/cnti-testcatalog/testsuite/pull/1899 had fixed the issue
