### ISSUE TITLE
[BUG] If k8s cluster is not configured then the user should informed to configure a cluster appropriately

### ISSUE THREAD

**Issue by HashNuke** [cnti-testcatalog/testsuite#1217]
### Describe the bug

If the k8s cluster is not configured, then the `setup` task throws an error about not being able to find any installation of `kubectl`.

<img width="1738" alt="image" src="https://user-images.githubusercontent.com/84005/153843362-624b77d9-17aa-4dbe-ab05-6c825ceee827.png">

### To Reproduce

1. Clear the KUBECONFIG env var
2. Run the `setup` task

### Environment info

Docker v20.10.10 on mac

### Expected behavior

If k8s cluster is not configured then the user should informed to configure a cluster appropriately

**Comment by lixuna** [comment]
@HashNuke  is this issue still relevant?
