### ISSUE TITLE
[BUG] Handle helm "INSTALLATION FAILED" error

### ISSUE THREAD

**Issue by HashNuke** [cnti-testcatalog/testsuite#1239]
## Describe the bug
When Helm install fails, Helm outputs an error message with a summary/reason for the failure.

Below are few examples of what the error lines might look like:
```
Error: INSTALLATION FAILED: failed to download "stable/prometheus-adapter"

Error: INSTALLATION FAILED: path "/github-runner-cnf-testsuite/cnf-testsuite/cnf-testsuite/cnfs/coredns/cnfs" not found

Error: INSTALLATION FAILED: parse error at (coredns/templates/deployment.yaml:16): function "sdfskfsdf" not defined
```

## Expected behaviour

Handle these errors in CNF Manager and other areas where `Helm.install` helper is being used.

**Comment by agentpoyo** [comment]
###  Acceptance Criteria 
---
### Documentation is updated:
- [x] USAGE.md documentation updated
   - [x] how to run
   - [x] Description, remediation and details 
       - [x] what the best practice is
       - [x] why are we testing this
- [ ] CATEGORIES updated

###  Common steps
- [x]  Find or create a K8s cluster to use
   - Talk with team for access to an existing cluster
   - [Kind K8s clusters](https://github.com/cncf/cnf-testsuite/blob/main/KIND-INSTALL.md) will work as well
- [x]  Set the KUBECONFIG environment variable for accessing the target K8s cluster
- [ ]  As a developer, Pull down latest version of CNF conformance test code from {FEATURE} branch
     - [ ]  Check that {FEATURE} Branch passes all A/C 
     - [ ]  Check that {FEATURE} Branch passes tests in GitHub Actions
- [x]  As a peer reviewer, check that PR passes in GitHub Actions
     - [x] if yes, merge PR to master
     - [x]  if no, make a comment and request that developer make changes to pass tests 
- [x]   As a peer reviewer, Pull down latest version of CNF conformance test code from `main` branch
- [ ]  Run `shards install`

### Update Prerequisite checker
- [ ] NA

### Added to overall points:
- [ ]  I see the test in the embedded points.yml as valid test score

### When I run `cnf_setup` I should not see generic errors of helm installation failures:
- [ ] Copy `./sample-cnfs/sample_coredns/cnf-testsuite.yml' to your pwd and edit it to use a bogus helm chart.
- [ ] Run `./cnf-testsuite cnf_setup cnf-config=./cnf-testsuite.yml`
- [ ] I can see Valid Error output about the failure.

### Screenshots of output:
- [ ] I can see a screenshots of the test and the kind clusters deleted

**Comment by agentpoyo** [comment]
@HashNuke I don't think this is what's expected, getting crystal type output with a mangled helm chart repo image name:

![1239_output](https://user-images.githubusercontent.com/14348948/160017226-879a3215-52ad-402b-abad-535f812d1ea2.png)

**Comment by agentpoyo** [comment]
@HashNuke can you look into reproducing this? We'll want to fix to push through peer review.

**Comment by lixuna** [comment]
ping @HashNuke

**Comment by lixuna** [comment]
@HashNuke @agentpoyo is this issue still relevant?
