### ISSUE TITLE
[Documentation]: Test case descriptions are not clear

### ISSUE THREAD

**Issue by CsatariGergely** [cnti-testcatalog/testsuite#1242]
**Describe the bug**
It is not clear from the [testcase descriptions](https://github.com/cncf/cnf-testsuite/blob/main/USAGE.md) what the tests are actually testing and what are the criteria for an OK or an NOW test. 

**To Reproduce**

1. Go to [testcase descriptions](https://github.com/cncf/cnf-testsuite/blob/main/USAGE.md) 
2. Read the test case descriptions

**Expected behavior**
Test case descriptions explain what is exactly tested and what are the criteria for an OK or a NOK test. 

**Screenshots**
N/A

**Device (please complete the following information):**
All

**How will this be tested? aka Acceptance Criteria (optional)**
N/A

**Comment by taylor** [comment]
Hi, @CsatariGergely. Thanks for reviewing.  It will be helpful to provide some more context and examples.  Please add those in a comment.

For the first question
>what the tests are actually testing

We are considering adding something minimal such as

https://github.com/cncf/cnf-testsuite/blob/main/USAGE.md#heavy_check_mark-to-check-if-any-containers-allow-for-privilege-escalation
**What does this control test**
Check that the allowPrivilegeEscalation field in securityContext of container is set to false.


Your next question is

> what are the criteria for an OK or an NOW test.

I'm not sure what you mean by "NOW".  Please explain what you are meaning with this question. Also provide an example or link to a specific example.

Thanks,
Taylor

**Comment by CsatariGergely** [comment]
Hi @taylor thanks for the answer. Yes, any explanation would be helpful, also in some test descriptions there are definitions, like "reasonable size" or "reasonable time", these should be quantified. 
On "NOW" I mean "NOK". For example in case of `To check if a CNF uses Kubernetes alpha APIs` it is not clear when the test fails. 
We started an analyzis of the test cases in Anuket RA2 [here](https://wiki.anuket.io/display/HOME/2022/03/01/Analyzis+of+CNCF+CNF+Testsuite+tests+for+RA2). We are still discussing the table, but you can see more feedback and questions there.

**Comment by taylor** [comment]
@CsatariGergely These will need to be broken down into smaller tickets.   For example these could go into one ticket:

What is the difference between rolling_downgrade and rolling_version_change?
What is the difference between rolled back rollback and rolling_downgrade?

The information is available.  That can be updated as one set to make sure it is clear.

**Comment by taylor** [comment]
BTW, @CsatariGergely some of these questions may be answered in the https://github.com/cncf/cnf-testsuite/blob/main/RATIONALE.md document

**Comment by CsatariGergely** [comment]
> BTW, @CsatariGergely some of these questions may be answered in the https://github.com/cncf/cnf-testsuite/blob/main/RATIONALE.md document

Huh, hoh. Thanks for the hint and mentioning this in the meeting we had. Maybe it would be good to link the rationale to the test case descriptions.

**Comment by CsatariGergely** [comment]
> @CsatariGergely These will need to be broken down into smaller tickets. For example these could go into one ticket:
> 
> What is the difference between rolling_downgrade and rolling_version_change? What is the difference between rolled back rollback and rolling_downgrade?
> 
> The information is available. That can be updated as one set to make sure it is clear.

@taylor I've created separate issues: 
- [#1321](https://github.com/cncf/cnf-testsuite/issues/1321)
- [#1322](https://github.com/cncf/cnf-testsuite/issues/1322)
- [#1337](https://github.com/cncf/cnf-testsuite/issues/1337)
- [#1338](https://github.com/cncf/cnf-testsuite/issues/1338)
- [#1339](https://github.com/cncf/cnf-testsuite/issues/1339)
- [#1340](https://github.com/cncf/cnf-testsuite/issues/1340)
- [#1341](https://github.com/cncf/cnf-testsuite/issues/1341)
