### ISSUE TITLE
[Documentation] Test titles are should indicate what is expected

### ISSUE THREAD

**Issue by CsatariGergely** [cnti-testcatalog/testsuite#1276]
**Describe the bug**
In case of some tests it is unclear from the test title what it the test testing.
Some examples:
* [To](https://github.com/cncf/cnf-testsuite/blob/main/USAGE.md#heavy_check_mark-to-check-if-the-cnf-has-a-reasonable-image-size) check if the CNF has a reasonable image size
* [To](https://github.com/cncf/cnf-testsuite/blob/main/USAGE.md#heavy_check_mark-to-check-if-the-cnf-have-a-reasonable-startup-time) check if the CNF have a reasonable startup time
* [To](https://github.com/cncf/cnf-testsuite/blob/main/USAGE.md#heavy_check_mark-to-check-if-the-cnf-has-multiple-process-types-within-one-container) check if the CNF has multiple process types within one container
* [To](https://github.com/cncf/cnf-testsuite/blob/main/USAGE.md#heavy_check_mark-to-check-if-the-cnf-has-multiple-microservices-that-share-a-database) check if the CNF has multiple microservices that share a database
* [To](https://github.com/cncf/cnf-testsuite/blob/main/USAGE.md#heavy_check_mark-to-check-if-any-containers-are-running-in-privileged-mode) check if any containers are running in [privileged mode](https://github.com/open-policy-agent/gatekeeper)
* [To](https://github.com/cncf/cnf-testsuite/blob/main/USAGE.md#heavy_check_mark-to-check-if-a-cnf-is-running-services-with-external-ips) check if a CNF is running services with external IP's
* [To](https://github.com/cncf/cnf-testsuite/blob/main/USAGE.md#heavy_check_mark-to-check-if-any-containers-are-running-as-a-root-user) check if any containers are running as a [root user](https://github.com/cncf/cnf-wg/blob/best-practice-no-root-in-containers/cbpps/0002-no-root-in-containers.md)
* [To](https://github.com/cncf/cnf-testsuite/blob/main/USAGE.md#heavy_check_mark-to-check-if-an-attacker-can-use-a-symlink-for-arbitrary-host-file-system-access) check if any containers allow for [privilege escalation](https://bit.ly/C0058_symlink_filesystem)
* [To](https://github.com/cncf/cnf-testsuite/blob/main/USAGE.md#heavy_check_mark-to-check-if-there-are-service-accounts-that-are-automatically-mapped) check if an attacker can use a [symlink](https://bit.ly/C0012_application_credentials) for arbitrary host file system access
* [To](https://github.com/cncf/cnf-testsuite/blob/main/USAGE.md#heavy_check_mark-to-check-if-there-are-service-accounts-that-are-automatically-mapped) check if there are [service accounts that are automatically mapped](https://bit.ly/C0012_application_credentials)
* [To](https://github.com/cncf/cnf-testsuite/blob/main/USAGE.md#heavy_check_mark-to-check-for-insecure-capabilities) check for insecure capabilities
* [To](https://github.com/cncf/cnf-testsuite/blob/main/USAGE.md#heavy_check_mark-to-check-for-dangerous-capabilities) check for dangerous capabilities
* [To](https://github.com/cncf/cnf-testsuite/blob/main/USAGE.md#heavy_check_mark-to-check-if-containers-have-hostpath-mounts) check if containers have hostPath mounts

**To Reproduce**

1. Go to https://github.com/cncf/cnf-testsuite/blob/main/USAGE.md
2. Try to figure out from the descriptions when the testcase will fail ;)
3. See error

**Expected behavior**
Test case description should indicate what is the expected behavior of the test case.

**Screenshots**
N/A

**Device (please complete the following information):**

- All

**How will this be tested? aka Acceptance Criteria (optional)**

Test case titles clearly indicate when the test case will pass.

**Comment by taylor** [comment]
@CsatariGergely we like the idea of tests indicating what is expected.  Some of them do this. We will make the adjustments for the remaining.  This is a feature request and I have updated the ticket to indicate that.

**Comment by kosstennbl** [comment]
New documentation format has expectations for test as a separate point.
