### ISSUE TITLE
[Documentation]: Some tests are not clear on service types

### ISSUE THREAD

**Issue by CsatariGergely** [cnti-testcatalog/testsuite#1277]
**Describe the bug**
Tests
* [To](https://github.com/cncf/cnf-testsuite/blob/main/USAGE.md#heavy_check_mark-to-check-if-the-cnf-exposes-any-of-its-containers-as-a-service) check if the CNF exposes any of its containers as a service
* [To](https://github.com/cncf/cnf-testsuite/blob/main/USAGE.md#heavy_check_mark-to-check-if-a-cnf-is-running-services-with-external-ips) check if a CNF is running services with external IP's
* [To](https://github.com/cncf/cnf-testsuite/blob/main/USAGE.md#heavy_check_mark-to-test-if-there-are-node-ports-used-in-the-service-configuration) test if there are node ports used in the service configuration

are mentioning services, but it is not clear if these are Kubernetes Services or just services in general and if these are Kubernetes Services it is not clear what Service Types are accepted.

**To Reproduce**

1. Go to ['...'](https://github.com/cncf/cnf-testsuite/blob/main/USAGE.md)
2. Read the test case descriptions
3. See error

**Expected behavior**
Test case descriptions should define if they mean Kubernetes Services or not and if yes they should define what Service Types are acceptable. 

**Screenshots**
N/A

**Device (please complete the following information):**

- All

**Comment by taylor** [comment]
@CsatariGergely 

[To check if the CNF exposes any of its containers as a servic](https://github.com/cncf/cnf-testsuite/blob/main/USAGE.md#heavy_check_mark-to-check-if-the-cnf-exposes-any-of-its-containers-as-a-service)

as the drop down says it checks to see if a CNF exposes its "services" as Kubernetes Services as documented in the K8s docs [here](https://kubernetes.io/docs/concepts/services-networking/service/)


The test [check if the CNF exposes any of its containers as a service](https://github.com/cncf/cnf-testsuite/blob/main/USAGE.md#heavy_check_mark-to-check-if-a-cnf-is-running-services-with-external-ips

**Comment by rgstori** [comment]
hi @Taylor - would it be possible to check for other Service types as well besides Nodeport? 
Anuket RA2 mandates that clusters _must_ support **Loadbalancer** and **ClusterIP**, and _should_ support **Nodeport** and **ExternalName**

**Comment by lixuna** [comment]
closing issue as stale - can be reopened if prioritized by community

**Comment by kosstennbl** [comment]
Current, joined documentation still has some ambiguous usages of the word "service", but after quick look through all docs - meaning can mostly be deduced from the context around the word.
IMO - the issue can be closed.

**Comment by martin-mat** [comment]
closing, if anybody considers it needs still doc adaptations, please reopen.
