### ISSUE TITLE
[Feature] Options to output results in JUnit and TAP formats

### ISSUE THREAD

**Issue by HashNuke** [cnti-testcatalog/testsuite#1304]
### Current functionality

* The results file is currently output in YAML format.
* The test results displayed on stdout follows no standard format.

### Supporting the following formats would be helpful

* [TAP output](https://testanything.org/)
* JUnit XML format - [This is a possible reference]((https://llg.cubic.org/docs/junit/))

### Unknowns to confirm

Check Jenkins and other CI tools to confirm how they consume the test outputs if provided in these formats.
* Should TAP output be printed to stdout?
* Should JUnit output be printed to stdout or output as a file?

**Comment by lixuna** [comment]
@HashNuke  can this issue be closed?
