### ISSUE TITLE
[Feature] create a combined test for cert that includes: rolling update, rolling version change and rolling downgrade

### ISSUE THREAD

**Issue by lixuna** [cnti-testcatalog/testsuite#1316]
**Is your feature request related to a problem? Please describe.**
- for cert, `rolling update`, `rolling version change` and `rolling downgrade` will be considered one test
- Note: this does not change `rollback` which will remain as is 

**Describe the solution you'd like**
- if a CNF passes the entire process, it gets the Normal score
- if a CNF fails any part of the process, it gets the Normal penalty
- update [LIST_OF_TESTS](https://github.com/cncf/cnf-testsuite/blob/main/docs/LIST_OF_TESTS.md#rolling-update)
- update [USAGE](https://github.com/cncf/cnf-testsuite/blob/main/USAGE.md#heavy_check_mark-to-test-if-the-cnf-can-perform-a-rolling-update)

**Comment by taylor** [comment]
https://github.com/cncf/cnf-testsuite/issues/804

**Comment by lixuna** [comment]
same question at https://github.com/cnti-testcatalog/testsuite/issues/804#issuecomment-1930415555

@taylor @agentpoyo @HashNuke have the "rolling---" tests been refactored? Can this issue and #804 be closed?

**Comment by agentpoyo** [comment]
> same question at [#804 (comment)](https://github.com/cnti-testcatalog/testsuite/issues/804#issuecomment-1930415555)
> 
> @taylor @agentpoyo @HashNuke have the "rolling---" tests been refactored? Can this issue and #804 be closed?

Yes. I we refactored the increase and decrease into one test but we can probably drop this one for now. Add back if the desire is there for a single combined test.
