### ISSUE TITLE
[Documentation]: Add documentation - Upgrade related terms are not explained in the the testcase descriptions

### ISSUE THREAD

**Issue by CsatariGergely** [cnti-testcatalog/testsuite#1321]
**Describe the bug**
It is not clear from the [testcase descriptions](https://github.com/cnti-testcatalog/testsuite/blob/main/USAGE.md) 
- What is the difference between rolling_downgrade and rolling_version_change?
- What is the difference between rolled back rollback and rolling_downgrade?

Description in [rationale](https://github.com/cncf/cnf-testsuite/blob/main/RATIONALE.md#to-check-if-a-cnf-version-can-be-downgraded-through-a-rolling_downgrade-rolling_downgrade) is unclear. 

**To Reproduce**

1. Go to [testcase descriptions](https://github.com/cncf/cnf-testsuite/blob/main/USAGE.md)
2. Read the test case descriptions

**Expected behavior**
Test case descriptions explain what are the differences.

**Comment by macaktom** [comment]
Basically, if I understood it correctly these tests ("rolling_update", "rolling_downgrade", "rolling_version_change") have simillar implementation, but test tag decides direction (rolling_update_test_tag -> new version, rolling_downgrade_test_tag -> older version). In that case is rolling_version_change even needed? In what context? Based on https://github.com/cnti-testcatalog/testsuite/blob/main/docs/LIST_OF_TESTS.md#rollback , it looks like as rolling_version_change is just a copy of rollback_downgrade test.

**Comment by taylor** [comment]
The description of what these tests are doing is still not clear https://github.com/cnti-testcatalog/testsuite/blob/main/docs/LIST_OF_TESTS.md#rollback

If they are doing different things and it is suggested to test both (rather than only keeping a subset) then the documentation should be updated to make things clear.

**Comment by lixuna** [comment]
@taylor is this related to https://github.com/cnti-testcatalog/testsuite/issues/1198 and https://github.com/cnti-testcatalog/testsuite/issues/1316?

**Comment by kosstennbl** [comment]
IMO, current documentation explains the difference between tests better that it was at the moment of this issue creation (although it could be done a bit clearer).
I think, that we need to redesign rolling_version_change and all related tests, and trying to clarify the documentation before that doesn't seem like a reasonable direction of efforts. Probably, the issue could be closed.
