### ISSUE TITLE
 [Documentation]: To check if a CNF uses Kubernetes alpha APIs test case description does not define when the tescase pass

### ISSUE THREAD

**Issue by CsatariGergely** [cnti-testcatalog/testsuite#1322]
**Describe the bug**
From the test case descriptions it is not clear when To check if a CNF uses Kubernetes alpha APIs test is OK? If the CNF uses alpha API-s or when it does not?

**Expected behavior**
Clarify the test case description.

**Comment by kosstennbl** [comment]
Current documentation makes this clear.
