### ISSUE TITLE
[BUG] No consistency among skipped tests to be present/absent in the results file

### ISSUE THREAD

**Issue by HashNuke** [cnti-testcatalog/testsuite#1327]
## Describe the bug
Some tests are included in the results yml file and some others are not.

## To Reproduce

1. Install the sample CNF at `sample-cnfs/sample_coredns`
2. Run workload tests `./cnf-testsuite workload`

Check results file for the following issues (also shown in the screenshots).

#### 1. `helm_deploy` would be displayed as skipped in the output but not in the results file

<img width="963" alt="CleanShot 2022-04-07 at 20 32 49@2x" src="https://user-images.githubusercontent.com/84005/162230402-3c97032a-1d3e-45a6-bb90-3be3964ad29b.png">

#### 2. `pod_dns_error` would be displayed as skipped in the output but is present in the results file

<img width="1002" alt="CleanShot 2022-04-07 at 20 29 32@2x" src="https://user-images.githubusercontent.com/84005/162229889-65b73f39-dd73-4a92-aca4-6c3728aee6da.png">

## Expected behavior
If any info/output for about a test is displayed in the STDOUT, then it should be included as part of the results file, along with the test status.

**Comment by lixuna** [comment]
@HashNuke  can this issue be closed?
