### ISSUE TITLE
[BUG] When `shared_database` crashes, it does not get added to the results YAML file

### ISSUE THREAD

**Issue by HashNuke** [cnti-testcatalog/testsuite#1334]
## Describe the bug

> *This might be the same behaviour with any other test that crashes. But I can only confirm it for `shared_database` for now.*

When `shared_database` crashes, it is not added to the results YAML file. Screenshot below.

![CleanShot 2022-04-07 at 22 12 33@2x](https://user-images.githubusercontent.com/84005/162255130-6bd945e6-b401-4103-9f97-99c35e6c8b50.png)

## To reproduce

1. Install the sample CNF at `sample-cnfs/sample_coredns` cnf
2. Run the workload tests `./cnf-testsuite workload`

## Expected behaviour
* Check if this error can be handled/rescued with a human readable error message.
* If the `shared_database` test crashes or fails, then the test should still be added to the results YAML file.

**Comment by HashNuke** [comment]
The cause of the crash was fixed as a part of another ticket (#1342). This ticket can be of lower priority.

**Comment by lixuna** [comment]
@HashNuke is this issue still relevant for CNTI?

**Comment by kosstennbl** [comment]
Fixed by #2045
