### ISSUE TITLE
[Documentation]: Description of To test if the CNF uses elastic volumes is not clear

### ISSUE THREAD

**Issue by CsatariGergely** [cnti-testcatalog/testsuite#1341]
**Describe the bug**
test case description [To test if the CNF uses elastic volumes](https://github.com/cncf/cnf-testsuite/blob/main/USAGE.md#heavy_check_mark-to-test-if-the-cnf-uses-elastic-volumes) does not define what an elastic volume is. The [rationale ](https://github.com/cncf/cnf-testsuite/blob/main/RATIONALE.md#to-test-if-the-cnf-uses-elastic-volumes-elastic_volumes) of the test case does not explain why rescheduling is a problem (or why it should not be a problem and how volumes affect on it).

**Expected behavior**
1 Define elastic volume in the test case description
2 Clarify rationale.

**Comment by kosstennbl** [comment]
Very similar to #1278, elastic_volumes lacks good documentation. Closed as duplicate.
