### ISSUE TITLE
[BUG] Update Cluster API Test to Check for Generic Resources, Support Multiple Kubeconfigs and Verify Target Cluster

### ISSUE THREAD

**Issue by denverwilliams** [cnti-testcatalog/testsuite#1354]
**Describe the bug**
The Cluster API Platform test currently works by looking at [non-generic resources](https://github.com/cncf/cnf-testsuite/blob/main/src/tasks/platform/platform.cr#L114) in order to determine if Cluster API is being used.

In order for the test to be more reliable, it should look at generic resources that remain constant under multiple different cluster api configurations, e.g the generic "kubeadmcontrolplanes" resource: `kubectl get kubeadmcontrolplanes`

Because the Cluster API management cluster has a different Kubeconfig from the cluster being managed by Cluster API, we need to support using a separate variable that will be used for interacting with the Cluster API management service. We can then alternate between the Management Cluster & Workload Cluster Kubeconfigs in order to determine if the workload cluster is being managed by Cluster API.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device (please complete the following information):**

- OS [e.g. Linux, iOS, Windows, Android]
- Distro [e.g. Ubuntu]
- Version [e.g. 18.04]
- Architecture [e.g. x86, arm]

**How will this be tested? aka Acceptance Criteria (optional)**

(optional: unnecessary for things like spelling errors and such)

Once this issue is address how will the fix be verified?

**Additional context**

---

NOTE: you can enable higher logging level output via the command line or env var. to help with debugging

```
# cmd line
./cnf-testsuite -l debug test

# make sure to use -- if running from source
crystal src/cnf-testsuite.cr -- -l debug test

# env var
LOGLEVEL=DEBUG ./cnf-testsuite test
```

Also setting the verbose option for many tasks will add extra output to help with debugging

```
crystal src/cnf-testsuite.cr test_name verbose
```

Check [usage documentation](https://github.com/cncf/cnf-testsuite/blob/main/USAGE.md) for more info about invoking commands and logging

**Comment by lixuna** [comment]
@denverwilliams @agentpoyo can this issue be closed?
