### ISSUE TITLE
[BUG] Update hardcoded_ip_addresses_in_k8s_runtime_configuration to support a manifest_directory

### ISSUE THREAD

**Issue by denverwilliams** [cnti-testcatalog/testsuite#1364]
**Describe the bug**
The hardcoded_ip_addresses_in_k8s_runtime_configuration test currently manually generates a manifest.yml from either the ```helm_directory``` or ```helm_chart arguments``` and does't support cnfs installed using the ```manifest_directory``` argument. This test should be updated to use the ```CNFManager.workload_resource_test(args, config)``` function so the test runs against the actual CNF runtime configuration, and so the test would also support cnfs is installed via ```manifest_directory```.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device (please complete the following information):**

- OS [e.g. Linux, iOS, Windows, Android]
- Distro [e.g. Ubuntu]
- Version [e.g. 18.04]
- Architecture [e.g. x86, arm]

**How will this be tested? aka Acceptance Criteria (optional)**

(optional: unnecessary for things like spelling errors and such)

Once this issue is address how will the fix be verified?

**Additional context**

---

NOTE: you can enable higher logging level output via the command line or env var. to help with debugging

```
# cmd line
./cnf-testsuite -l debug test

# make sure to use -- if running from source
crystal src/cnf-testsuite.cr -- -l debug test

# env var
LOGLEVEL=DEBUG ./cnf-testsuite test
```

Also setting the verbose option for many tasks will add extra output to help with debugging

```
crystal src/cnf-testsuite.cr test_name verbose
```

Check [usage documentation](https://github.com/cncf/cnf-testsuite/blob/main/USAGE.md) for more info about invoking commands and logging

**Comment by lixuna** [comment]
@taylor is this issue still relevant for CNTI?
