### ISSUE TITLE
[BUG] Fix duplicate usage of the increase_decrease_capacity test

### ISSUE THREAD

**Issue by denverwilliams** [cnti-testcatalog/testsuite#1385]
**Describe the bug**
The increase_decrease_capacity test is used in multiple places. The [runtime](https://github.com/cncf/cnf-testsuite/blob/main/src/tasks/workload/runtime.cr#L7) category uses the  increase_decrease_capacity, but it is then separately called again under the [compatibility](https://github.com/cncf/cnf-testsuite/blob/main/src/tasks/workload/compatibility.cr#L11) category.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device (please complete the following information):**

- OS [e.g. Linux, iOS, Windows, Android]
- Distro [e.g. Ubuntu]
- Version [e.g. 18.04]
- Architecture [e.g. x86, arm]

**How will this be tested? aka Acceptance Criteria (optional)**

(optional: unnecessary for things like spelling errors and such)

Once this issue is address how will the fix be verified?

**Additional context**

---

NOTE: you can enable higher logging level output via the command line or env var. to help with debugging

```
# cmd line
./cnf-testsuite -l debug test

# make sure to use -- if running from source
crystal src/cnf-testsuite.cr -- -l debug test

# env var
LOGLEVEL=DEBUG ./cnf-testsuite test
```

Also setting the verbose option for many tasks will add extra output to help with debugging

```
crystal src/cnf-testsuite.cr test_name verbose
```

Check [usage documentation](https://github.com/cncf/cnf-testsuite/blob/main/USAGE.md) for more info about invoking commands and logging

**Comment by lixuna** [comment]
@denverwilliams what is the runtime category? We do not list it in the usage, or any documentation for cnf test suite. Can we remove the category entirely?

**Comment by lixuna** [comment]
@HashNuke @agentpoyo @denverwilliams is still issue still relevant?
