### ISSUE TITLE
[BUG]: Duplicate tests about privileged containers

### ISSUE THREAD

**Issue by CsatariGergely** [cnti-testcatalog/testsuite#1409]
**Describe the bug**
Both [To check if any containers are running in privileged mode](https://github.com/cncf/cnf-testsuite/blob/main/USAGE.md#heavy_check_mark-to-check-if-any-containers-are-running-in-privileged-mode) and [To check if there are any privileged containers](https://github.com/cncf/cnf-testsuite/blob/main/USAGE.md#heavy_check_mark-to-check-if-there-are-any-privileged-containers) are testing the same thing. 

**Expected behavior**
Remove duplicated tests

**Comment by agentpoyo** [comment]
https://github.com/cncf/cnf-testsuite/issues/1200 already pointed out that these were likely duplicates. One was introduced using the upstream Kubescape tool within cnf-testsuite.

**Comment by lixuna** [comment]
closing as duplicate
