### ISSUE TITLE
[BUG] When volumes like configmaps, downwardAPI & emptyDir are mounted as volumes, they should be ignored during elastic volume checks

### ISSUE THREAD

**Issue by HashNuke** [cnti-testcatalog/testsuite#1419]
> *This issue surfaced after #1417 was resolved in a working branch.*

## Describe the bug
When volumes like configmaps, downwardAPI & emptyDir are mounted as volumes, they should be ignored during elastic volume checks.

The list of volume types in Kubernetes are available [here](https://kubernetes.io/docs/concepts/storage/volumes). We should decide what volume types to ignore and what we should expect to be elastic to pass the test.

## To Reproduce
1. Checkout branch `1398-main`
2. Install the CNF `sample_nonroot`, which has no volumes defined in the manifest.
3. The `elastic_volumes` test would fail. Expected result is skip.

#### For the `sample-elastic-volume` CNF, the volumes detected are in the screenshot

<img width="956" alt="CleanShot 2022-05-02 at 18 18 06@2x" src="https://user-images.githubusercontent.com/84005/166238287-88bcb394-1e2d-4ba2-b806-77a097f18768.png">

#### For the `sample_nonroot` CNF, the volumes detected are in the screenshot below

<img width="961" alt="CleanShot 2022-05-02 at 18 26 25@2x" src="https://user-images.githubusercontent.com/84005/166238341-b38033f3-6a76-4ba9-92e3-006923de5892.png">

**Comment by HashNuke** [comment]
Removing the certification tag. Will prioritize this at a later time. For now updating the spec test to match the result. Added a todo note in part of the code to mention the unhandled scenario.

**Comment by lixuna** [comment]
@HashNuke is still issue still relevant?
