### ISSUE TITLE
[Feature] Console Summary should Display Number of Tests SKIPPED or N/A

### ISSUE THREAD

**Issue by agentpoyo** [cnti-testcatalog/testsuite#1456]
**Describe the solution you'd like**
The current summary results on the console output during a `cert` command tells you the number of tests passed but it should also do a summary of the number of tests that either skipped or were n/a.

Example output now:
```
RESULTS SUMMARY              
  - 37 of 56 total tests passed
  - 13 of 13 essential tests passed
Results have been saved to results/cnf-testsuite-results-20220509-183233-897.yml
```

**Describe alternatives you've considered**
It would be nice to see when tests are skipped or N/A in the summary, example output below:

```
RESULTS SUMMARY              
  - 37 of 56 total tests passed
  - 13 of 13 essential tests passed
  - 2 essential tests were skipped
  - 1 test was N/A
Results have been saved to results/cnf-testsuite-results-20220509-183233-897.yml
```

**Comment by lixuna** [comment]
@agentpoyo  is this issue still relevant for CNTI?
