### ISSUE TITLE
[BUG] Remove Log.info wrappers when running shell commands in spec tests

### ISSUE THREAD

**Issue by HashNuke** [cnti-testcatalog/testsuite#1495]
## Describe the bug
Running shell commands in `Log.info { }` would result in the command being skipped when the log level is higher or not set.
So when the log level is higher, then the spec test would fail.

<img width="1305" alt="CleanShot 2022-06-08 at 18 38 34@2x" src="https://user-images.githubusercontent.com/84005/172624339-bc5b4efa-1c99-4503-be94-2d380574eb63.png">

**Comment by macaktom** [comment]
I can look into this task.
