### ISSUE TITLE
[Feature] Refactor the Results Summary for `cert` console and results log 

### ISSUE THREAD

**Issue by agentpoyo** [cnti-testcatalog/testsuite#1497]
**Is your feature request related to a problem? Please describe.**
The summary results can cause confusion based on the different types of tests within the `cert` command when running the certification tests.

**Describe the solution you'd like**
The types of tests should be broken down to clarify what passed and what failed, eg.:

```
Summary:
Total tests checked: 57
Essential tests: 10 of 15 passed
Normal tests: 20 of 30 passed
Bonus tests: 5 of 12 passed 
```
The console and the results log should reflect these tests broken down by type and the number that passed.

This is what the console output looks like now:
```
RESULTS SUMMARY                                                                                                       
  - 37 of 56 total tests passed                                                                                                                                                                       
  - 13 of 14 essential tests passed 
  - 
  ```
And this is the Results Summary in the results log file:
```
total_passed: 39 of 56
essential_passed: 12 of 14
```

**Comment by agentpoyo** [comment]
@taylor @lixuna @wavell @denverwilliams @HashNuke 

In the example output provided, we'll still see reduced number of totals for each category, essentials, normal, bonus if any are skipped or n/a. Even now the essentials have 15 tests and we'll find the output as 10 out of 14 passed. 

```
Essential tests: 10 of 15 passed
Normal tests: 20 of 30 passed
Bonus tests: 5 of 12 passed 
```

Perhaps the above would be less confusing if only provided the number passed and remove the "out of X" , eg.:

```
Essential tests: 10 passed
Normal tests: 20 passed
Bonus tests: 5 passed 
```

They can view failed, skipped or NA in the results file.

Thoughts?

**Comment by taylor** [comment]
I think we should get additional input from new eyes on this @agentpoyo.  End-users like MATRIXX also.  

An alternative view that we need to provide for input is the one showing the totals with non-hidden.

cc: @denverwilliams @wavell @HashNuke

**Comment by taylor** [comment]
@agentpoyo Please post all 3 options into separate comments and then we can have folks give 👍🏻 for the ones they like.

**Comment by agentpoyo** [comment]
Option 2:

```
Summary:
Total tests checked: 57
Essential tests: 10 passed
Normal tests: 20 passed
Bonus tests: 5 passed 
```

**Comment by agentpoyo** [comment]
Option 3 (I can't recall the actual totals for each type):

```
Summary:
Total tests checked: 57
Essential tests: 10 passed of 15 total
Normal tests: 20 passed of 30 total 
Bonus tests: 5 passed of 18 total
```

**Comment by agentpoyo** [comment]
Option 4:

```
Summary:
Total tests checked: 57
Essential tests: 9 passed, 1 failed, 2 skipped, 3 n/a
Normal tests: 20 passed, 8 failed, 1 skipped, 1 n/a
Bonus tests: 5 passed, 10 failed, 2 skipped, 1 n/a
```

**Comment by agentpoyo** [comment]
I voted Option 4.

**Comment by taylor** [comment]
> Option 3 (I can't recall the actual totals for each type):
> 
> ```
> Summary:
> Total tests checked: 57
> Essential tests: 10 passed of 15 total
> Normal tests: 20 passed of 30 total 
> Bonus tests: 5 passed of 18 total
> ```


@agentpoyo Please add  a description for each of these.  For instance if this is for not changing totals.. do please say something about that.

**Comment by agentpoyo** [comment]
> @agentpoyo Please add a description for each of these. For instance if this is for not changing totals.. do please say something about that.

Done @taylor

**Comment by agentpoyo** [comment]
Option 5 (use of % for passed tests):

```
Summary:
Total tests checked: 57
Essential tests: 80% passed
Normal tests: 70% passed
Bonus tests: 25% passed
```

**Comment by agentpoyo** [comment]
Perhaps vote on your top 2 out of the options? @taylor

**Comment by taylor** [comment]
> Option 1 (the total passed for each test category will be reduced if there's any skipped, n/a and bonus tests that actually failed):
> 
> ```
> Summary:
> Total tests checked: 57
> Essential tests: 10 of 15 passed
> Normal tests: 20 of 30 passed
> Bonus tests: 5 of 12 passed 
> ```

reduce some of the total test to show a reduction happened.  Example

Summary:
Total tests checked: 57
Essential tests: 10 of 15 passed
Normal tests: 20 of **28** passed
Bonus tests: 5 of 12 passed

**Comment by taylor** [comment]
> > Option 1 (the total passed for each test category will be reduced if there's any skipped, n/a and bonus tests that actually failed):
> > ```
> > Summary:
> > Total tests checked: 57
> > Essential tests: 10 of 15 passed
> > Normal tests: 20 of 30 passed
> > Bonus tests: 5 of 12 passed 
> > ```
> 
> reduce some of the total test to show a reduction happened. Example
> 
> Summary: Total tests checked: 57 Essential tests: 10 of 15 passed Normal tests: 20 of **28** passed Bonus tests: 5 of 12 passed

I disagree with someone having to look up in an external document what the "scores" mean.  Eg. Why is normal test reduced?  Now I have to go research or open a ticket.

**Comment by taylor** [comment]
Another option.  Show percentage then more details. Also do this in the results file to make it easy to check the percentage passed for each type (essential, normal, bonus)

Summary:
---
Total tests checked: 57
Essential tests: 80%
 - 9 passed, 1 failed, 2 skipped, 3 n/a
Normal tests: 75%
- 20 passed, 8 failed, 1 skipped, 1 n/a
Bonus tests: 30%
- 5 passed, 10 failed, 2 skipped, 1 n/a

**Comment by wavell** [comment]
Option 7 - Show grade only

Summary:
---
Total tests checked: 57
Final Grade: 90%, Passed
Essential tests: 9 passed, 1 failed, 2 skipped, 3 n/a
Normal tests:  20 passed, 8 failed, 1 skipped, 1 n/a
Bonus tests:  5 passed, 10 failed, 2 skipped, 1 n/a

**Comment by wavell** [comment]
Option 8: Show Grade, leave out details

Summary:
Total tests checked: 57
Final Grade: 90%, Passed
Essential tests: 10 passed
Normal tests: 20 passed
Bonus tests: 5 passed

**Comment by denverwilliams** [comment]
I put my two votes on Option 7 & 8.

It's a summary and seems confusing to put too much detailed information in there, so I'd have a higher preference for option 8. If they want to know the details of the score composition, that's not really a summary and should be in the results log only.

But, if having the detailed scoring is a must in the summary, then Option 7 seems like minimal & high level way of doing it.

**Comment by lixuna** [comment]
@taylor is this issue still relevant for CNTI?
