### ISSUE TITLE
[Documentation] Document minimum tools requirements along with recommended versions

### ISSUE THREAD

**Issue by agentpoyo** [cnti-testcatalog/testsuite#1609]
**Describe the bug**
It's not clear on what tools (eg. helm) are actually supported based on minimum version.

Need to test and verify what are the minimum required versions cnf-testsuite works/functions but also provide recommended versions (what versions are being used to actively test new or latest versions of ncf-testsuite)

**Comment by agentpoyo** [comment]
Some notes on tools used:

kind v1.23 image recommended. Versions newer work but `sig_term_handled` test works specifically with v1.23 image. It  is not part of `cert` or `workload` currently.

crystal v1.0.0 minimum, recommended version is v1.6.0. Tested and verified up to v1.6.2.

**Comment by lixuna** [comment]
hi @agentpoyo can this issue be closed?
