### ISSUE TITLE
[Feature] Move git library to separate repo

### ISSUE THREAD

**Issue by williscool** [cnti-testcatalog/testsuite#1615]
Is your feature request related to a problem? Please describe.
The current libraries in ./util are being maintained solely by Vulk.

Describe the solution you'd like

Put git that is currently in the ./utils directory into its own repo

Set up github actions for each git

Library should be searchable in https://crystalshards.org/

related to https://github.com/cncf/cnf-testsuite/issues/943

**Comment by lixuna** [comment]
@HashNuke @agentpoyo has this been completed? Can the issue be closed?
