### ISSUE TITLE
[Documentation] create LIST OF TESTS for upcoming release, v0.34.0

### ISSUE THREAD

**Issue by lixuna** [cnti-testcatalog/testsuite#1658]
## Short description:
- update or add a new file for the list of tests included in the upcoming release, v0.34.0 
- Example: https://github.com/cncf/cnf-testsuite/blob/main/docs/LIST_OF_TESTS.md

**Comment by taylor** [comment]
List of tests should be updated each release

**Comment by lixuna** [comment]
See #1843 for current request. Closing this issue as outdated.
