### ISSUE TITLE
[BUG] Cleanup results output for bonus tests.

### ISSUE THREAD

**Issue by denverwilliams** [cnti-testcatalog/testsuite#1664]
**Describe the bug**
Bonus tests are currently included in the test output and this skews the total points in a way that makes the totals look invalid. We should hide or cleanup the bonus tests so the total points don't get skewed.

https://github.com/cncf/cnf-testsuite/issues/1649

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device (please complete the following information):**

- OS [e.g. Linux, iOS, Windows, Android]
- Distro [e.g. Ubuntu]
- Version [e.g. 18.04]
- Architecture [e.g. x86, arm]

**How will this be tested? aka Acceptance Criteria (optional)**

(optional: unnecessary for things like spelling errors and such)

Once this issue is address how will the fix be verified?

**Additional context**

---

NOTE: you can enable higher logging level output via the command line or env var. to help with debugging

```
# cmd line
./cnf-testsuite -l debug test

# make sure to use -- if running from source
crystal src/cnf-testsuite.cr -- -l debug test

# env var
LOGLEVEL=DEBUG ./cnf-testsuite test
```

Also setting the verbose option for many tasks will add extra output to help with debugging

```
crystal src/cnf-testsuite.cr test_name verbose
```

Check [usage documentation](https://github.com/cncf/cnf-testsuite/blob/main/USAGE.md) for more info about invoking commands and logging

**Comment by martin-mat** [comment]
I don't understand the intention of this issue. Bonus tests have 1 point when passing and 0 if failing as defined in points.yml which should reflect importance of bonus tests.
Or is the intention to have an option to leave out bonus tests completely from execution?

**Comment by lixuna** [comment]
@taylor please review the comment above

**Comment by taylor** [comment]
@denverwilliams was this when bonus points had a negative number when failing?  If so this is resolved.  Please close if it is no longer an issue.
