### ISSUE TITLE
[BUG] Add default resource polices for Cluster Tools

### ISSUE THREAD

**Issue by denverwilliams** [cnti-testcatalog/testsuite#1674]
**Describe the bug**
Cluster tools fails to install on GKE Clusters because default resource polices haven't' been defined.

```
root@cnfqa1:~/cnf-testsuite# kubectl create -f tools/cluster-tools/manifest.yml 
Warning: Autopilot set default resource requests for DaemonSet default/cluster-tools, as resource requests were not specified. See http://g.co/gke/autopilot-defaults.
Error from server ([denied by autogke-disallow-hostnamespaces]|[denied by autogke-disallow-privilege]|[denied by autogke-no-write-mode-hostpath]): error when creating "tools/cluster-tools/manifest.yml": admission webhook "gkepolicy.common-webhooks.networking.gke.io" denied the request: GKE Policy Controller rejected the request because it violates one or more policies: {"[denied by autogke-disallow-hostnamespaces]":["enabling hostNetwork is not allowed in Autopilot. Requested by user: '', groups: 'system:authenticated'."],"[denied by autogke-disallow-privilege]":["container cluster-tools is privileged; not allowed in Autopilot"],"[denied by autogke-no-write-mode-hostpath]":["hostPath volume containerd-volume in container cluster-tools is accessed in write mode; disallowed in Autopilot. Requested by user: '', groups: 'system:authenticated'.","hostPath volume proc in container cluster-tools is accessed in write mode; disallowed in Autopilot. Requested by user: '', groups: 'system:authenticated'.","hostPath volume dockerd-volume in container cluster-tools is accessed in write mode; disallowed in Autopilot. Requested by user: '', groups: 'system:authenticated'."]}
```
**To Reproduce**

**Expected behavior**

**Screenshots**

**Device (please complete the following information):**

- OS [e.g. Linux, iOS, Windows, Android]
- Distro [e.g. Ubuntu]
- Version [e.g. 18.04]
- Architecture [e.g. x86, arm]

**How will this be tested? aka Acceptance Criteria (optional)**

(optional: unnecessary for things like spelling errors and such)

Once this issue is address how will the fix be verified?

**Additional context**

---

NOTE: you can enable higher logging level output via the command line or env var. to help with debugging

```
# cmd line
./cnf-testsuite -l debug test

# make sure to use -- if running from source
crystal src/cnf-testsuite.cr -- -l debug test

# env var
LOGLEVEL=DEBUG ./cnf-testsuite test
```

Also setting the verbose option for many tasks will add extra output to help with debugging

```
crystal src/cnf-testsuite.cr test_name verbose
```

Check [usage documentation](https://github.com/cncf/cnf-testsuite/blob/main/USAGE.md) for more info about invoking commands and logging

**Comment by martin-mat** [comment]
since cluster-tools have been removed in
https://github.com/cncf/cnf-testsuite/commit/a7137ab6fa0e9fe9afe678310ec1e2facb4dd03e
I guess this issue can be closed as not relevant anymore.
