### ISSUE TITLE
[BUG] Error "no resource names found" when multiple tgz of CNF downloads exist in the cnf-testsuite directory

### ISSUE THREAD

**Issue by agentpoyo** [cnti-testcatalog/testsuite#1683]
**Describe the bug**
"no resource names found" when running `cert` or `workload` tests on new kind cluster on latest main branch when multiple tgz files are leftover within the cnf-testsuite working directory.

This might occur when testing different versions for rollback testing functionality.

**To Reproduce**
Checkout `main` branch and build from source the cnf-testsuite.
Create a kind cluster, 2 node preferably.
Use one of the sample cnfs, like sample-corednds-cnf  with `cnf-config`
Run `./cnf-testsuite cert`
See output with tests errors on console.

**Expected behavior**
Should not see the error "no resource names found" and cnf-testsuite should cleanup multiple tgz files it generates during the test.

**Screenshots**
<img width="942" alt="image001" src="https://user-images.githubusercontent.com/14348948/195386107-f9813254-d456-4a6d-9a78-bdf942ca1d9a.png">

**Comment by agentpoyo** [comment]
[no_resource_output.log](https://github.com/cncf/cnf-testsuite/files/9766699/no_resource_output.log)

**Comment by agentpoyo** [comment]
Removing the duplicate coredns tgz files resolved the errors seen.

**Comment by HashNuke** [comment]
Informed on standup. Picking this up since it has been a while since opening.

**Comment by agentpoyo** [comment]
@HashNuke 

Run it once with a CNF for coredns and then change the version in the config to pull down another version. This should make it so there are multiple tgz files downloaded.

**Comment by lixuna** [comment]
@agentpoyo @HashNuke is this issue still relevant?

**Comment by agentpoyo** [comment]
> @agentpoyo @HashNuke is this issue still relevant?

Need to test and reproduce. It's a finicky one I think, doesn't happen often from what I recall.
