### ISSUE TITLE
[Workload] Test if cluster Permissions and resource names are present for all operators. (OLM Specific)

### ISSUE THREAD

**Issue by wavell** [cnti-testcatalog/testsuite#1685]
## Title: [Workload] Test if cluster Permissions and resource names are present for all operators.

**Is your workload test idea related to a problem? Please describe.**
- security

**Describe the solution you'd like**
- Test if clusterPermissions and resource names are present for all operators.

**Test Category Name**
- Security

**Type of test (static or runtime)**
- runtime

---

### Documentation tasks:
- [ ] Update [installation instructions](https://github.com/cncf/cnf-testsuite/blob/main/install.md) if needed
- [ ] Update [Test Categories md](https://github.com/cncf/cnf-testsuite/blob/main/TEST-CATEGORIES.md) if needed
- [ ] Update [USAGE md](https://github.com/cncf/cnf-testsuite/blob/main/USAGE.md) if needed
  - [ ] How to run
  - [ ] Description and details
    - [ ] What the best practice is
    - [ ] Why are we testing this
  - [ ] Remediation steps if test does not pass

### QA tasks

Dev Review:

- [ ] walk through A/C
- [ ] do you get the expected result?
- [ ] if yes,
  - [ ] move to `Needs Peer Review` column
  - [ ] create Pull Request and follow check list
  - [ ] Assign 1 or more people for peer review
- [ ] if no, document what additional tasks will be needed

Peer review:

- [ ] walk through A/C
- [ ] do you get the expected result?
- [ ] if yes,
  - [ ] move to `Reviewer Approved` column
  - [ ] Approve pull request
- [ ] if no,
  - [ ] document what did not go as expected, including error messages and screenshots (if possible)
  - [ ] Add comment to pull request
  - [ ] request changes to pull request

testname: operator_cluster_permissions

# prerequisites
- [ ] create sample operator with privileged permissions (sample_operator_w_cluster_permissions)
  -- should be in a helm chart
- [ ] create sample operator with no privileged permissions (sample_operator_no_cluster_permissions)
  -- should be in a helm chart
# development criteria

- [ ] Create spec for sample_operator_w_cluster_permissions test
    -- should use operator_cluster_permissions and expect failure
- [ ] Create spec for sample_operator_no_cluster_permissions test
    -- should use operator_cluster_permissions and expect success
- [ ] Create test named  operator_cluster_permissions
 
# acceptance criteria

- [ ] Install cnf sample_operator_w_cluster_permissions
- [ ] run `./cnf-testsuite operator_cluster_permissions`
- [ ] test should fail
- [ ] Unintall cnf sample_operator_w_cluster_permissions
- [ ] Install cnf sample_operator_no_cluster_permissions
- [ ] run `./cnf-testsuite operator_cluster_permissions`
- [ ] test should pass

what is an operator
https://kubernetes.io/docs/concepts/extend-kubernetes/operator/
making an operator with a custom language
https://www.weave.works/blog/creating-custom-kubernetes-operators

What are cluster permissions and resources in relations to the operator framework:
see: https://hackmd.io/LmoP70lUS26hcP_wRvLJzA
https://olm.operatorframework.io/docs/advanced-tasks/operator-scoping-with-operatorgroups/
https://olm.operatorframework.io/docs/concepts/crds/clusterserviceversion/#example-clusterserviceversion

making an operator
https://nubenetes.com/kubernetes-operators-controllers/#writing-kubernetes-operators-and-controllers
https://stackoverflow.com/questions/69032478/how-to-list-installed-kubernetes-operators-and-delete-them-via-kubectl
https://betterprogramming.pub/build-a-kubernetes-operator-in-10-minutes-11eec1492d30
https://developers.redhat.com/articles/2021/09/07/build-kubernetes-operator-six-steps
https://www.techtarget.com/searchitoperations/tutorial/How-to-build-a-Kubernetes-operator
https://developer.ibm.com/learningpaths/kubernetes-operators/develop-deploy-advanced-operator-janusgraph/how-to-make-an-operator/

**Comment by wavell** [comment]
points: 
watson: 8
denver: 8
drew: 8

**Comment by lixuna** [comment]
@agentpoyo has this test been peer reviewed?

**Comment by agentpoyo** [comment]
> @agentpoyo has this test been peer reviewed? It's still in the "In Progress" column. I did not list this in 0.38.0 release notes due to lack of A/C notes

@lixuna,

Verified with Denver that the "Add the Operator Test" work was completed but not the "check permissions", related task requirement. We'll need to create another issue just for the work completed as this one might not get completed anytime soon.

**Comment by lixuna** [comment]
hi @agentpoyo can this issue be closed?
