### ISSUE TITLE
[BUG] When specifying tests to skip while running `cert` for debugging purposes, it's not skipping the tests

### ISSUE THREAD

**Issue by agentpoyo** [cnti-testcatalog/testsuite#1688]
**Describe the bug**
When a test is skipped with the `~cert_testname` option, cnf-testsuite is not skipping the actual test. This only occurs when running `cert` as workload tests being skipped are actually skipped.

**To Reproduce**
Setup cnf-testsuite and when you run `cert`, also specify the test `~cert_cni_compatible` test to skip the `cni_compatible` test.

**Expected behavior**
This should skip the test and not attempt to run it.

**Comment by lixuna** [comment]
@HashNuke is this issue still relevant?
