### ISSUE TITLE
[DOC] Add a FAQ to address implementation errors of 'command not found' when following our install instructions for LAMDA and other environments

### ISSUE THREAD

**Issue by agentpoyo** [cnti-testcatalog/testsuite#1710]
**Describe the doc update**
LAMDA and other environments for implementing cnf-testsuite in automation and CI/CD pipelines might result in the PATH not getting setup, forcing the users to add the full path to where the binary is installed.

Need to add this to our documentation and FAQ for end users who encounter the issue.

**Comment by lixuna** [comment]
@agentpoyo Is this issue still relevant?

**Comment by agentpoyo** [comment]
> @agentpoyo Is this issue still relevant?
>

Yes. It's nothing urgent and it's an environment issues rather than testsuite issue. We should get it added to the FAQ at some point.

**Comment by kosstennbl** [comment]
To me, it is not clear what is the issue.
If it is a problem with locating testsuite binary outside of directories mentioned in PATH env, then I'm not sure that it is related to testsuite FAQ.
IMO, issue can be closed.

**Comment by martin-mat** [comment]
Adding testsuite binary to PATH looks too generic issue to be handled even in docs of the testsuite. Closing. If anybody sees a sense in it, one can reopen / add a PR.
