### ISSUE TITLE
[BUG] elastic volume fails when no volumes are used on GKE cluster

### ISSUE THREAD

**Issue by agentpoyo** [cnti-testcatalog/testsuite#1713]
**Describe the bug**
TVK running on a GKE cluster.
Would like to understand the issue of Elastic Volume-related failure. TrilioVault is a stateless application but the second test confirms that local storage volume is not found and then we again check if the volumes used are elastic or non-elastic which fails since there are no volumes.

**To Reproduce**
Run cert after installing the TVK CNF on GKE cluster.

**Comment by lixuna** [comment]
hi @agentpoyo is this issue still relevant?
