### ISSUE TITLE
CNF Tests Priority

### ISSUE THREAD

**Issue by Smitholi67** [cnti-testcatalog/testsuite#1724]
It would be valuable to CNF vendors using the CNF Test Suite, if there was a unique priority assigned to every test.  

Currently, CNF test suite tests are categorized as Essential, Normal, or Bonus for CNCF Certified CNF purposes (documented here:  https://github.com/cncf/cnf-certification/blob/main/instructions.md)

As a community it would be valuable for us to form and document an opinion on the unique priority of each test.  This is only partially accomplished today with the categories of Essential, Normal, and Bonus.   Essential tests are higher priority than Normal, and Normal are higher priority than Bonus.  

By assigning a unique priority ranking to each test, this would provide guidance to CNF vendors where to focus their development efforts FIRST as they create (or continue developing) cloud native networking applications/functions.

Possible solutions could be:
1) Documentation of priority rank for each test **OR**
2) Ordering of test execution in the Test Suite with a clear priority ranking within the existing categories (e.g. Essential test 1, Essential test 2, ......Normal Test 1, Normal Test 2,  .....Bonus Test 1, Bonus Test 2, ....)  **OR**
3) A preview into future CNF Tiers such as Gold/Silver/Bronze and the criteria for each.  Not sure this works without a live program for these tiered options, but the point is to help make expectations known.

**Comment by lixuna** [comment]
@Smitholi67 Is this issue more relevant to the CNTI Certification group? 

If so, please close this issue in the test suite and add a new issue to https://github.com/lfn-cnti/certification

A new implementation issue can be opened in the future if needed.
