### ISSUE TITLE
[BUG] Several CNCF Security Test Cases do not run behind a proxy.

### ISSUE THREAD

**Issue by vinaysha11983741** [cnti-testcatalog/testsuite#1752]
**Describe the bug**
Several CNCF security Test cases do not execute within corporate proxy network. 
Tried with both online and airgapped methods.

Error generated is : 
**Error connecting to 'github.com:443': Operation timed out**

Currently there is no guidance on how to execute cncf testsuite with a proxy.

**To Reproduce**
Execute cncf security test case behind a proxy
**cnf-testsuite security**
**cnf-testsuite symlink_file_system**

**Device (please complete the following information):**

- OS Linux
- Distro Ubuntu
- Version 20.04

Error:
/usr/share/crystal/src/gc/boehm.cr:110:5 in 'io'
/usr/share/crystal/src/http/client.cr:671:19 in 'send_request'
/usr/share/crystal/src/http/client.cr:651:20 in 'perform'
/workspace/lib/sam/src/sam/task.cr:44:29 in 'call'
/workspace/lib/sam/src/sam/task.cr:44:29 in 'call'
/workspace/lib/sam/src/sam/task.cr:44:29 in 'call'
/workspace/lib/sam/src/sam/task.cr:44:29 in 'call'
/workspace/lib/sam/src/sam/execution.cr:20:7 in '__crystal_main'
/usr/share/crystal/src/crystal/main.cr:110:5 in 'main'
src/env/__libc_start_main.c:94:2 in 'libc_start_main_stage2'
Error connecting to 'github.com:443': Operation timed out
(optional: unnecessary for things like spelling errors and such)

Once this issue is address how will the fix be verified?

**Additional context**

---

NOTE: you can enable higher logging level output via the command line or env var. to help with debugging

```
# cmd line
./cnf-testsuite -l debug test

# make sure to use -- if running from source
crystal src/cnf-testsuite.cr -- -l debug test

# env var
LOGLEVEL=DEBUG ./cnf-testsuite test
```

Also setting the verbose option for many tasks will add extra output to help with debugging

```
crystal src/cnf-testsuite.cr test_name verbose
```

Check [usage documentation](https://github.com/cncf/cnf-testsuite/blob/main/USAGE.md) for more info about invoking commands and logging

**Comment by lixuna** [comment]
@agentpoyo is this issue a bug or is it a new enhancement to support this use case?

**Comment by agentpoyo** [comment]
> @agentpoyo is this issue a bug or is it a new enhancement to support this use case?

Don't think so. This is an environment type issue where they run the testsuite, their workstation and or cluster needs to redirect all network traffic through a proxy if there is one that is required for outside external access.

**Comment by agentpoyo** [comment]
> @agentpoyo is this issue a bug or is it a new enhancement to support this use case?

But we did open an issue regarding this: https://github.com/cnti-testcatalog/testsuite/issues/1568

I'll update this to be a enhancement and possibly outside contributors can take a stab at implementation.

**Comment by agentpoyo** [comment]
I'll close this and we can track any progress in #1568
