### ISSUE TITLE
[BLOG] Zombie Blog (On testing for zombies)

### ISSUE THREAD

**Issue by wavell** [cnti-testcatalog/testsuite#1763]
**Is your feature request related to a problem? Please describe.**
Zombie Blog (On testing for zombies)

**Describe the solution you'd like**
Zombie Blog (On testing for zombies)
Idea: script that downloads 100 containers from dockerhub and gets the percentage of containers that are "zombie proof"

See: https://github.com/cncf/cnf-testsuite/issues/1719

**Comment by lixuna** [comment]
Published on MAR 01, 2023

https://www.infoq.com/articles/cloud-native-network-functions-concern/
