### ISSUE TITLE
[Feature: EPIC] New essential tests - zombies, reaping, init system

### ISSUE THREAD

**Issue by wavell** [cnti-testcatalog/testsuite#1795]
**Is your feature request related to a problem? Please describe.**

The testing of microservices currently verifies that there is only one process type per container (#156).  The weight of this test (10 of 15) may be too heavy for those CNFs that need high performance and were originally engineered to have multiple process types within one container.

**Describe the solution you'd like**
The *new version* of the certification should include three new microservice tests: #1719, #1722 and #8.  The rational for these can be found at: https://www.infoq.com/articles/cloud-native-network-functions-concern/
With three new tests, the weighting of the original test (#156) will be reduced by having three other microservice tests added into the essential tests.  This will make the multiple process type test 1/4th of its original weighting.

**Comment by lixuna** [comment]
closing issue in test catalog repo. to be discussed in cnti certification focus area. see new issue (certification # 87)
