### ISSUE TITLE
[BUG] `cni_compatible` fails to create a cilium cluster

### ISSUE THREAD

**Issue by HashNuke** [cnti-testcatalog/testsuite#1796]
## Describe the bug

> *Found this issue when validating code changes for #1782*

The `cni_compatible` test fails to create a cilium cluster

![image](https://github.com/cncf/cnf-testsuite/assets/84005/c35d24b8-1391-4590-bf5c-a29d91b6c02e)

```shell
# Below is the command that the testsuite is using in the screenshot above.
# The paths to kind are different due to the changes in `bug/1782`.
# But the same issue occured when running the binary compiled from main branch too.

/home/akash/.cnf-testsuite/tools/kind/kind create cluster \
--name cilium-test \
--config /home/akash/.cnf-testsuite/tools/kind/disable_cni.yml \
--image kindest/node:v1.21.1 --kubeconfig /home/akash/.cnf-testsuite/tools/kind/cilium-test_admin.conf
```

Attempting to create the cilium cluster using the same command as the testsuite works when used outside of the testsuite.

![image](https://github.com/cncf/cnf-testsuite/assets/84005/e30c6c7d-4205-443c-a857-a3a96c5b9a52)

## To Reproduce

```shell
./cnf-testsuite setup
./cnf-testsuite cnf_setup cnf-path=./sample-cnfs/sample-coredns-cnf/cnf-testsuite.yml
LOG_LEVEL=debug ./cnf-testsuite cni_compatible
```

**Expected behavior**
The `cni_compatible` test should pass.

**Device (please complete the following information):**

Ubuntu 22.04 running on a DigitalOcean server.
<img width="757" alt="CleanShot 2023-06-14 at 21 14 50@2x" src="https://github.com/cncf/cnf-testsuite/assets/84005/b9108163-308b-43d6-b451-ed0b678ac300">

**Comment by lixuna** [comment]
@HashNuke is still issue still relevant?

**Comment by lixuna** [comment]
@HashNuke is still issue still relevant?
