### ISSUE TITLE
[DOC] Fix verbiage for SOURCE INSTALL docs for Supported Crystal Version

### ISSUE THREAD

**Issue by agentpoyo** [cnti-testcatalog/testsuite#1815]
**Describe the bug**
The [Source Install](https://github.com/cncf/cnf-testsuite/blob/main/INSTALL.md) and https://github.com/cncf/cnf-testsuite/blob/main/SOURCE-INSTALL.md docs refer to supporting crystal-lang v1.6.0 or greater. 

We need to address the docs to state specific versions as future versions might require updates to shard modules in use and other code that might break in future versions of crystal lang.

**Expected behavior**
Docs need to reflect actual supported versions or state that greater versions are likely supported but could result in undesirable results as 3rd party modules might not support the latest crystal-lang versions.

**Comment by lixuna** [comment]
@agentpoyo is still issue still relevant?
