### ISSUE TITLE
[BUG] embedded_files/points.yml: "tags" is a list by semantic, but not by yaml syntax

### ISSUE THREAD

**Issue by martin-mat** [cnti-testcatalog/testsuite#1865]
**Describe the bug**
in embedded_files/points.yml, I can see tags listed this way:
`
tags: configuration, dynamic, workload, cert, bonus
`
which means that 'tags' contains a string of comma-separated values. Which logically means it is a list. So yaml syntax should respect the semantics, it should be a list in yaml as well, not a string.

Current state makes:
1. points.yaml unintuitive, requiring keeping logical list in a non-standard way as a comma-separated string. Confusing for yaml-aware people.
2. handling in crystal code unnecessary complex, requiring to parse comma-separated string instead of using a list parsed directly by crystal yaml library

**To Reproduce**

**Expected behavior**
Have tags as a list:
```
tags:
  - configuration
  - dynamic
  - workload
  - cert
  - bonus
```

or alternativelly
`tags: [configuration, dynamic, workload, cert, bonus]`

and refactor/simplify tags handling in  src/tasks/utils/points.cr

**Comment by horecoli** [comment]
I can take this issue :)

**Comment by HashNuke** [comment]
@martin-mat Thank you for reporting this. Good catch ~! 👍

@horecoli I took a look at your work-in-progress branch. Looks like you are making the changes required ❤️.
I'll review again it once you send a PR.

**Comment by horecoli** [comment]
Thanks @HashNuke . I will create a PR, but I want to run spec tests first.

**Comment by HashNuke** [comment]
Completed via PR. Closing issue.
