### ISSUE TITLE
[Documentation] Update GitHub description, README, etc to reflect new CNTI program

### ISSUE THREAD

**Issue by lixuna** [cnti-testcatalog/testsuite#1873]
**Describe the update:**
- Update GitHub description, README, etc to reflect new CNTI program
- https://wiki.lfnetworking.org/display/LN/Test+Catalog

**Describe why update is needed**
- CNF WG (and CNCF’s related Cloud Native Telco efforts) has moved to LFN (see [wiki](https://wiki.lfnetworking.org/display/LN/Cloud+Native+Telecom+Networking+Initiative))

**Additional context**
- https://wiki.lfnetworking.org/pages/viewpage.action?pageId=113213592
- #1851

**Comment by agentpoyo** [comment]
https://github.com/cnti-testcatalog/testsuite/pull/1870 addresses the actual URL change for the repo migration.
