### ISSUE TITLE
[BUG] Failing platform observability spec tests 

### ISSUE THREAD

**Issue by macaktom** [cnti-testcatalog/testsuite#1878]
**Describe the bug**
Platform observability spec tests are failing, when running them (individually or via command `crystal spec`).

**To Reproduce**
`crystal spec`
or
`crystal spec ./spec/platform/observability_spec.cr`

**Expected behavior**
All observability spec tests should pass.

**Screenshots**
![image](https://github.com/cnti-testcatalog/testsuite/assets/43893713/c48cfa62-dea9-4ba9-8f2b-d5b1338764ba)

**Device (please complete the following information):**

- OS Linux
- Distro Ubuntu
- Version 22.04
- Architecture x86
- Crystal 1.11.1
- Kubernetes v1.28.3

**How will this be tested? aka Acceptance Criteria (optional)**
For verification successfully running `crystal spec ./spec/platform/observability_spec.cr` should be enough.

**Additional context**

**Comment by agentpoyo** [comment]
See https://github.com/cnti-testcatalog/testsuite/issues/1880#issuecomment-1932700437, I think this may be related.

**Comment by denverwilliams** [comment]
@macaktom This spec test was installing the node_exporter from an old helm repo, and the chat no longer supported the more recent k8s releases. 
```
Helm.helm_repo_add("prometheus-community","https://prometheus-community.github.io/helm-charts")
resp = `#{helm} install node-exporter prometheus-community/prometheus-node-exporter
```

The spec has been updated to install the exporter from the current prometheus-community repo to fix.
