### ISSUE TITLE
[BUG] Failing curl_install spec tests

### ISSUE THREAD

**Issue by macaktom** [cnti-testcatalog/testsuite#1879]
**Describe the bug**
Curl install spec tests are failing, when running them (individually or via command crystal spec).

**To Reproduce**
`crystal spec`
or
`crystal spec ./spec/curl_install_spec.cr`

**Expected behavior**
All curl_install spec test should pass.
**Screenshots**
![image](https://github.com/cnti-testcatalog/testsuite/assets/43893713/590bd77c-f5c5-4231-a06a-5f4514e86819)

**Device (please complete the following information):**

- OS Linux
- Distro Ubuntu
- Version 22.04
- Architecture x86
- Crystal 1.11.1
- Kubernetes v1.28.3

**How will this be tested? aka Acceptance Criteria (optional)**
For verification successfully running `crystal spec ./spec/curl_install_spec.cr` should be enough.

**Additional context**

**Comment by agentpoyo** [comment]
This is failing due to the repo URL change. We got updates coming that are combined with the current fix for CI/CD github runner fixes.

**Comment by denverwilliams** [comment]
@macaktom @agentpoyo 
Fixed by PR #1883
