### ISSUE TITLE
[BUG] Incorrect logic of elastic_volumes and database_persistence tests

### ISSUE THREAD

**Issue by kosstennbl** [cnti-testcatalog/testsuite#1884]
**Describe the bug**
elastic_volumes and database_persistence has issue with `elastic_volumes_used` and `elastic_statefulset` variables: they will become and stay true even if not of the tested resources have desired properties. 
Incorrect results would be achieved if i.e. there is two pods, where one has PVC with StorageClaim with elastic property, and second one - has a static one. In this situation test will pass, where, from my point of view, it shouldn't.

Second issue is with database_persistence test: why does it test for elastic volumes? To me it seems redundant as we are testing that in elastic_volumes. Also, it seems to be missing part of its core idea: to test if mysql is being ran as a StatefulSet, not to check that there is any StatefulSets with elastic volumes.

It could be that I'm not understanding something in the logic of these testcases, or misinterpreting their goals. If so - please correct me.

**Expected behavior**
Make tests expect elastic volumes for all resources and fail if volume is not elastic.
Reconsider testing for elasticity in database_persistence
Depending on the goals of database_persistence, consider redisigning it to test for all mysql images to be used as pods in statefulset.

**Comment by HashNuke** [comment]
## `database_persistence` test

I agree - the functionality needs improvement.

From what I see in the test right now - any statefulset being part of the CNF is being picked up and checked for usage of elastic volumes.

*Here's what I see we could do:* If MySQL is part of the CNF,
* Check if it is part of a statefulset.
* Also check if it is using elastic volumes.

Performing these two checks would help display appropriate test failure messages. Right now the result messages for this test refer to elastic volumes. Instead the messages should be about databases and persistence.

* On success:
  * `PASSED: CNF uses database with cloud-native persistence`
* On failure:
  * `FAILED: CNF uses database without cloud-native persistence`
* On skip (when MySQL is not installed)
  * `SKIPPED: CNF does not use database`

Note: We only check for MySQL for now. If we come across any organization that uses Postgres and wants that to be tested, we could add support for Postgres too.

## `elastic_volumes`

I checked the test and I agree again. Looking for ANY volume to be elastic to pass the test seems like a bug. The vars seem to be set once if the conditions are satisfied and never marked as false for failing further checks.

**Comment by wavell** [comment]
Heres the original ticket:
https://github.com/cnti-testcatalog/testsuite/issues/1030

```
K8s Database persistence test: if a mysql (or any popular database) image is installed:

if a statefulset with a elastic persistent volume is used: 5 points
if used directly with elastic persistent volumes: 3 points
if statefulset with a local persistent volume is used: 0 points
if used local volumes: -1 (caught by existing volume tests)
```

This was before the current point system
The idea was to reward the perfect world (statefulset with elastic) but to allow for non statefulset use cases as the non optimal case.  The true failure was supposed to be local volumes used with a database.
@kosstennbl @HashNuke

**Comment by kosstennbl** [comment]
To me - it seems, that without check for statefulsets - this testcase becomes an incomplete copy of elastic_volumes testcase.

In your opinion, should this output case for 3 points be returned?
