### ISSUE TITLE
[MAINTENANCE] remove non_root_user test along with Falco

### ISSUE THREAD

**Issue by martin-mat** [cnti-testcatalog/testsuite#1891]
**Describe the software update**
non_root_user test is duplicated by non_root_containers. Remove non_root_user. Along with that, all Falco-related code can be removed as well as non_root_user test is the only reason why Falco is used.

**Describe why update is needed**
remove duplicate test and decrease code complexity

**What version is in use now?**

**What version is the latest version and/or which version you will use for the update?**

**Additional context**
#1648

**Comment by HashNuke** [comment]
Completed via PR. Closing issue.
