### ISSUE TITLE
[BUG] Consider only the CNF's resources for the `privileged` test that checks for containers running in privileged mode

### ISSUE THREAD

**Issue by HashNuke** [cnti-testcatalog/testsuite#1906]
## Description

The more recent tests added to the testsuite consider only the CNF's resources when running workload tests.

But some older tests like the `privileged` test, consider all of the cluster resources.

The reference here is to the call being made to `KubectlClient::Get.privileged_containers` in the `privileged` test.

![CleanShot 2024-02-23 at 08 38 52@2x](https://github.com/cnti-testcatalog/testsuite/assets/84005/7cfaa363-76c2-48b5-ab2a-500f33e7fd21)

## Possible improvements

1. Consider only the CNFs resources for the test.
2. The allowlist option being considered in the test could be removed in this case.

## Notes on filtering CNF's resources

There are two ways to filter resources of the CNF being tested.

1. The `workload_resource_test` helper being used in a lot of tests help loop through resources of the CNF currently being tested. This is useful when the workflow or the third-party tool offers fine-grained controls to test specific resources.
2. If the third-party tool does not offer fine-grained controls of what to test and instead requires that a full cluster-scan be run, then the filtration logic can look like what we do in the Kyverno and Kubescape integrations (similar implementations).

For examples of filtering CNF's resources refer to the following:
* `filter_failures_for_cnf_resources` [in the Kyverno module](https://github.com/cnti-testcatalog/testsuite/blob/24e048b7308fefc131cd47968f7d5c0fc4950d24/src/tasks/utils/kyverno.cr#L134)
* `filter_cnf_resources` [in the Kubescape module](https://github.com/cnti-testcatalog/testsuite/blob/24e048b7308fefc131cd47968f7d5c0fc4950d24/src/tasks/utils/kubescape.cr#L54)

**Comment by horecoli** [comment]
I can take a look at this.

**Comment by kosstennbl** [comment]
Fixed in #1928
