### ISSUE TITLE
[BUG] Unintuitive output of install_cluster_tools/uninstall_cluster_tools within the context of spec tests.

### ISSUE THREAD

**Issue by svteb** [cnti-testcatalog/testsuite#1926]
**Describe the bug**
While running the spec tests with `LOG_LEVEL=info` the `cluster_setup_spec.cr` tests have quite the jarring output, printing out a caught exception, this output comes from the `./cnf-testsuite install_cluster_tools/uninstall_cluster tools` command that is called as part of the tests.  Without reading and understanding the code, one might assume that the test is somehow failing.

```
desc "Install CNF Test Suite Cluster Tools"
task "install_cluster_tools" do |_, args|
  Log.info { "install_cluster_tools" }
  begin
    ClusterTools.install
  rescue e : ClusterTools::NamespaceDoesNotExistException 
    raise "#{e.message}. please run cnf-testsuite setup!"          # <-- offending line
  end
end
```

**To Reproduce**
1. `export LOG_LEVEL=info`
2. `crystal spec ./spec/cluster_setup_spec.cr`
3. Observe the output.

**Expected behavior**
It is hard to say what the best code practice here is, but I believe that printing out the exception is quite unnecessary and misleading (especially in the context of spec tests), considering it is followed by the remediation: "please run cnf-testsuite setup!". I am unsure if removing the `#{e.message}.` part could be detrimental elsewhere, if anyone has better ideas (or thinks this is completely irrelevant 😄) please comment.

**Jarring spec test output**
![image](https://github.com/cnti-testcatalog/testsuite/assets/133103846/79e4f30e-0904-4dd0-b11f-0c98c1977736)

**Comment by macaktom** [comment]
Good catch, I looked into it and think that we should remove `#{e.message}` from that line and if stack trace is needed, then we could just use `Log.debug {"#{e.message}"}` to print that for debugging purposes.
