### ISSUE TITLE
[BUG] curl_install.sh failing on problem with missing file

### ISSUE THREAD

**Issue by ptacemic** [cnti-testcatalog/testsuite#1929]
**Describe the bug**
curl_install.sh is failing as it's trying to download following tarball 
https://github.com/cnti-testcatalog/testsuite/releases/download/v0.46.0/cnf-testsuite-v0.46.0.tar.gz
and failed with 

+ LATEST_RELEASE=v0.46.0
+ mkdir -p /home/ubuntu/.cnf-testsuite
+ curl --silent -L https://github.com/cnti-testcatalog/testsuite/releases/download/v0.46.0/cnf-testsuite-v0.46.0.tar.gz -o /home/ubuntu/.cnf-testsuite/cnf-testsuite.tar.gz
+ tar -C /home/ubuntu/.cnf-testsuite -xf /home/ubuntu/.cnf-testsuite/cnf-testsuite.tar.gz
tar: This does not look like a tar archive
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now

**To Reproduce**

1. Follow installation guide
2. Run curl command
   source <(curl -s https://raw.githubusercontent.com/cnti-testcatalog/testsuite/main/curl_install.sh)

**Expected behavior**
Binary installation should pass

**Screenshots**

**Device (please complete the following information):**

- OS Virtualbox
- Distro Ubuntu
- Version 22.04 LTS
- Architecture x86

**Comment by agentpoyo** [comment]
Appears the binary was detached from the assets for the release. This should be fixed now. 

@ptacemic , do you mind verifying again?

Thanks.

**Comment by ptacemic** [comment]
doesn't work for me, I can download binary manually from this URL:
 https://github.com/cnti-testcatalog/testsuite/releases/download/v0.46.0/cnf-testsuite-v0.46.0.tar.gz

but curl_install.sh is now failing on this URL not found
https://api.github.com/repos/cncf/cnf-testsuite/releases/latest

```
{
    "message": "Not Found",
    "documentation_url": "https://docs.github.com/rest/releases/releases#get-the-latest-release"
}

```

and hence script failes

```
:~/cnf-testsuite$ bash -xe curl_install.sh
+ set -o errexit
+ [[ /bin/bash == *\b\a\s\h* ]]
+ SHELL_PROFILE=/home/ptacemic/.bashrc
+ SHELL_DOT_DIR=/home/ptacemic/.bash.d/
+ '[' '' = cleanup ']'
++ get_latest_release cncf/cnf-testsuite
++ curl --silent https://api.github.com/repos/cncf/cnf-testsuite/releases/latest
++ grep '"tag_name":'
++ sed -E 's/.*"([^"]+)".*/\1/'
+ LATEST_RELEASE=
+ mkdir -p /home/ptacemic/.cnf-testsuite
+ curl --silent -L https://github.com/cncf/cnf-testsuite/releases/download//cnf-testsuite-.tar.gz -o /home/ptacemic/.cnf-testsuite/cnf-testsuite.tar.gz
+ tar -C /home/ptacemic/.cnf-testsuite -xf /home/ptacemic/.cnf-testsuite/cnf-testsuite.tar.gz
tar: This does not look like a tar archive

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

**Comment by agentpoyo** [comment]
You likely need to do a git pull to refresh your cloned repository. I could not reproduce the error you are seeing since it appears the curl_install.sh script you got locally on your machine is still pointing to the old REPO url on github.

The latest curl_install.sh script points to cnti-testcatalog/testsuite, if you run this, it should pull the latest release:

`source <(curl -s https://raw.githubusercontent.com/cnti-testcatalog/testsuite/main/curl_install.sh)`

You may have to make the binary executable once it downloads into ~/.cnf-testsuite/:

```
cd ~/.cnf-testsuite/
chmod +x cnf-testsuite
```

**Comment by ptacemic** [comment]
thank you, it works now. I think we can close this bug report
