### ISSUE TITLE
[Documentation] update docs/LIST_OF_TESTS.md to reflect CNTI Certification V2 tests

### ISSUE THREAD

**Issue by lixuna** [cnti-testcatalog/testsuite#1930]
**Describe the update**
- the docs/LIST_OF_TESTS.md file is out of date - showing tests as of v0.27.0
- the certification release will is pending (early-April TBD)

**Describe why update is needed**
- the docs/LIST_OF_TESTS.md file should reflect all tests that are available in the newest release (to include all Essential, Normal, Bonus tests)
- Proposed List of CNTI Certification V2.0 Essential Tests is available at: https://docs.google.com/document/d/1ysgGfiG2qEXJUyxksVnuzSeKTcp9V5-SId65_nwDRDg/edit#bookmark=id.v7b25uo39cjo

**What version is in use now?**
- the latest release of docs/LIST_OF_TESTS.md  is v0.27.0

**Additional context**
- Anuket is linking to our list of tests in their [documentation](https://cntt.readthedocs.io/projects/rc2/en/stable-nile/chapters/chapter05.html)

**Comment by martin-mat** [comment]
What is scope of this ticket? Is that only updating links to the code/implementation?
If so then perhaps this can be done only 1.0.0 tag is applied.
@lixuna 
@taylor

**Comment by lixuna** [comment]
The goal of this ticket is to make sure the documentation (List of Tests) accurately reflects all tests that are included in the test suite at the time of v1.0.0 release, including updated links to the test code.

Ideally, this documentation would be updated with each new release.
