### ISSUE TITLE
[Documentation] update results log to reflect CNTI Certification V2 tests

### ISSUE THREAD

**Issue by lixuna** [cnti-testcatalog/testsuite#1932]
**Describe the update**
- update results log to reflect new tests to be included in new H1 2024 certification binary release

**Describe why update is needed**
- Proposed List of CNTI Certification V2.0 Essential Tests is available at: https://docs.google.com/document/d/1ysgGfiG2qEXJUyxksVnuzSeKTcp9V5-SId65_nwDRDg/edit#bookmark=id.v7b25uo39cjo
- the H1 2024 certification binary release (v1.0.0) will be released early-April 2024 (TBD)

**What version is in use now?**
- The current certification binary release is pointing to an outdated version of the test suite, https://github.com/cncf/cnf-testsuite/releases/tag/v0.29.1
- Update results log if needed to support new certification tests in v1.0.0 release

**Additional context**
- https://github.com/lfn-cnti/certification/blob/main/reviewing.md

**Comment by martin-mat** [comment]
I don't see anything special to be adapted in the result log; just stdout printouts (adapted in #1939). Am I missing anything?

**Comment by lixuna** [comment]
@agentpoyo @taylor @HashNuke please advise

**Comment by lixuna** [comment]
@agentpoyo @taylor @HashNuke @wavell @denverwilliams please review @martin-mat's comment above
