### ISSUE TITLE
[BUG] cnf_setup command is not working correctly in case of failing cnf creation

### ISSUE THREAD

**Issue by horecoli** [cnti-testcatalog/testsuite#1937]
**Describe the bug**
It looks like that cnf_setup doesn't work correctly. It is finishing successfully even if cnf is not created or it is not in running state.
Example with envoy:
`./cnf-testsuite cnf_setup cnf-config=example-cnfs/envoy/cnf-testsuite.yml`
`Successfully created directories for cnf-testsuite`
`cnf-testsuite namespace already exists on the Kubernetes cluster`
`cnf setup online mode`
`Successfully setup envoy`
`cnf setup online mode complete`

`ubuntu@vm:~/test/testsuite$ kubectl get pods`
`No resources found in default namespace.`

Example coredns:
`./cnf-testsuite cnf_setup cnf-config=example-cnfs/coredns/cnf-testsuite.yml`
`Successfully created directories for cnf-testsuite`
`cnf-testsuite namespace already exists on the Kubernetes cluster`
`cnf setup online mode`
`Successfully setup coredns`
`cnf setup online mode complete`

`ubuntu@vm:~/git/cnf-testsuite$ kubectl get pods`
`NAME                               READY   STATUS             RESTARTS   AGE`
`coredns-coredns-7b6b6c5d6d-4hlvk   0/1     ImagePullBackOff   0          3m59s`

**To Reproduce**
I found out this issue when I had some issues with image pulling. So for reproduction is needed little bit broken environment to have issues with pulling (maybe wrong dns setting).

**Expected behavior**
cnf_setup command should fail or at least return correct exit status.

**Device (please complete the following information):**

- OS [e.g. Linux, iOS, Windows, Android]
- Distro [e.g. Ubuntu]
- Version [e.g. 18.04]
- Architecture [e.g. x86, arm]

**How will this be tested? aka Acceptance Criteria (optional)**

(optional: unnecessary for things like spelling errors and such)

Once this issue is address how will the fix be verified?

**Additional context**

**Comment by kosstennbl** [comment]
#2114 Merged
