### ISSUE TITLE
[BUG] Update all Kubernetes version in Gates (stop pinning v1.23 EOL)

### ISSUE THREAD

**Issue by collivier** [cnti-testcatalog/testsuite#1948]
**Describe the bug**

kindest/node:v1.23.17 is hard-coded in gate but K8S v1.23 has been EOL for a while.

**To Reproduce**

See https://github.com/search?q=repo%3Acnti-testcatalog%2Ftestsuite%20kindest%2Fnode%3A&type=code

**Expected behavior**

No kindest/node pinned

**How will this be tested? aka Acceptance Criteria (optional)**

Github actions must pass

**Comment by HashNuke** [comment]
I posted a comment on the PR with some notes as to why the version was pinned.
