### ISSUE TITLE
[Documentation] Update commands for all cnf-examples

### ISSUE THREAD

**Issue by haskojur** [cnti-testcatalog/testsuite#1951]
### Description
Currently there is difference in commands between installation, usage guides and example-cnf guides. Installation and usage guides have following format:
`./cnf-testsuite setup`
And cnf-examples have this format:
`crystal src/cnf-testsuite.cr setup`

This steps are not consistent and can cause a confusion.

### Suggestion
We should update the documentation of all example-cnfs, so all commands will have the same format: `crystal src/cnf-testsuite.cr setup`

### Benefits
Commands in example-cnfs and installation/usage guides have same format, remove inconsistency.

**Comment by HashNuke** [comment]
Thank you for the PR. Merged it.
