### ISSUE TITLE
[Feature] Add test case identifiers for tests being executed to console output and more informative console output

### ISSUE THREAD

**Issue by martin-mat** [cnti-testcatalog/testsuite#1958]
**Is your feature request related to a problem? Please describe.**
Currently, console output does not provide any information about what testcase is being executed/has been executed.
Example:

1. start test execution

$ ./cnf-testsuite single_process_type

(test is being executed, user is not informed about any action ongoing)

2. tests finishes

$ ./cnf-testsuite single_process_type
✔️  🏆PASSED: Only one process type used ⚖👀
$

(test execution finished, user is informed about the test result, but no explicit test identifier (single_process_type) given. User needs to guess what test case it was (from the result note "Only one process type used")

**Describe the solution you'd like**
Give more information about what is going on and an exact test description.
Example:
1. start test execution

$ ./cnf-testsuite single_process_type
🎬 Testing "single_process_type"

(test is being executed, user is not informed about any action ongoing)

2. tests finishes

$ ./cnf-testsuite single_process_type
🎬 Testing: single_process_type
✔️  🏆PASSED: single_process_type ⚖👀
$

or

$ ./cnf-testsuite single_process_type
🎬 Testing: single_process_type
✖️  🏆FAILED: single_process_type ⚖👀
$

Eventually, the "Testing" line can be replaced on then console with the result line after the test is executed. But that is probably not feasible now as the console output is mixed with logs.

Where needed, keep additional information for failed tests (where it is now)

Note that this is related to "console output". Increasing log level is not a solution for this as logging is (or rather should be) a different mechanism with potentially routing to different files than the console output.

**Comment by HashNuke** [comment]
+1 for the "Testing" line.

**Comment by martin-mat** [comment]
> Yes this would help ~!
> 
> * We can prefix it "PASSED: [test name] Hello world"
> * Or we can suffix it to the end of the message Like "PASSED: Hello world (test name)"

 "PASSED: [test name] Hello world" 
looks good.
