### ISSUE TITLE
[BUG] cni_compatible installs obsolete cluster (v1.21 and no cgroup v2 support). Part of cert ? 

### ISSUE THREAD

**Issue by collivier** [cnti-testcatalog/testsuite#1965]
**Describe the bug**

cni_compatible installs a very EOL Kubernetes version (3y old)
```
INFO -- cnf-testsuite: KindManager#create_cluster(online) stderr: Creating cluster "calico-test" ...
 • Ensuring node image (kindest/node:v1.21.1) 🖼   ...
 ✓ Ensuring node image (kindest/node:v1.21.1) 🖼 
 • Preparing nodes 📦   ...
 ✗ Preparing nodes 📦 
```

More this kind/kubernetes version fails vs cgroup v2 because of lack of support
`ERROR: failed to create cluster: could not find a log line that matches "Reached target .*Multi-User System.*|detected cgroup v1"`

Please note that the test keeps failing and doesn't stop after the first issue
```
I, [2024-04-11 12:53:31 +02:00 #34997]  INFO -- cnf-testsuite: Helm.install output:
I, [2024-04-11 12:53:31 +02:00 #34997]  INFO -- cnf-testsuite: Helm.install stderr: Error: INSTALLATION FAILED: Kubernetes cluster unreachable: stat /home/cedric/.cnf-testsuite/tools/kind/calico-test_admin.conf: no such file or directory
```

I would consider that cert won't install any additional cluster as it is a big issue out of a lab environment.

**To Reproduce**
```
./cnf-testsuite setup 
./cnf-testsuite cnf_setup cnf-config=example-cnfs/coredns
./cnf-testsuite cni_compatible -l debug
```

**Expected behavior**

cni_compatible removed from cert and updated to an active kubernetes version.

**Comment by martin-mat** [comment]
Since cni_compatible is not part of the certification criterions (not "essential"), from my point of view it is ok to be removed from "cert" category.

**Comment by agentpoyo** [comment]
I see no issues in removing this from the `cert` option and from the list of tests for the certification prior to the v1.0.0 release we have planned. Once any bugs are fixed it can be added back, despite not being an `essential` test, I still think it's a valuable test. It could likely be rewritten and improved.

Thoughts @wavell @denverwilliams @HashNuke ?

**Comment by taylor** [comment]
This test when running with the `cert` command crashes with an error vs returning PASS/FAIL.


Suggestions on cert call for this test longer term
- Update test to use current stable K8s releases (eg. v1.29 at this time)
- Don't start up a new cluster

Suggestions for short term:
- Remove from list of tests turn with cert command

**Comment by taylor** [comment]
See https://github.com/cnti-testcatalog/testsuite/pull/2006/files
