### ISSUE TITLE
[BUG] pod_dns_error is always SKIPPED when "containerd" runtime is used

### ISSUE THREAD

**Issue by martin-mat** [cnti-testcatalog/testsuite#1977]
**Describe the bug**
The test is always SKIPPED in case "containerd" container runtime is used.

"containerd" is a precondition for the k8s platform for cnf-testsuite.

**To Reproduce**

1. configure platform accordingly to  https://github.com/cnti-testcatalog/testsuite/blob/main/INSTALL.md#pre-requisites
2. execute pod_dns_error test
3. the test result is "SKIPPED: pod_dns_error docker runtime not found"

**Expected behavior**
test passes or fails depending on test result, even when using containerd runtime

**Comment by martin-mat** [comment]
Consider removing pod_dns_error from the certification criterions until this it fixed. It is meaningless to have it there currently.

**Comment by taylor** [comment]
TODO:
1. Open a ticket in the certification repo to remove this as a test for certification
2. Remove pod_dns_error from the cert command in the test suite (grouping of tests for the certification) 
3. Fix this test
   - Check upstream Litmus test to see if it supports containerd
   - Update testsuite test


Reference: Added to Certification list based on https://docs.google.com/document/d/1ysgGfiG2qEXJUyxksVnuzSeKTcp9V5-SId65_nwDRDg/edit
- Pod DNS errors - pod_dns_error
- [testsuite/docs/LIST_OF_TESTS.md at v0.45.0 · cnti-testcatalog/testsuite (github.com)](https://github.com/cnti-testcatalog/testsuite/blob/v0.45.0/docs/LIST_OF_TESTS.md#pod-dns-errors)
