### ISSUE TITLE
Option to run Cert command for only Essential Tests

### ISSUE THREAD

**Issue by Smitholi67** [cnti-testcatalog/testsuite#1997]
At present, the CNTi Test Suite cert command executes all tests (Essential, Normal, and Bonus).

A feature (or parameter) that allowed an end user to specify the execution of Essential tests only would be valuable.  For example, an end user may be running the CNTi Test Suite in a CI/CD pipeline.  They may want to regularly execute the Essential tests to ensure continual conformance with Essentials.  At present, running Cert in the pipeline causes all tests to execute which consumes resources and takes time.

While there are workarounds, excluding tests one by one, this is not optimal.

**Comment by kosstennbl** [comment]
Working on it (can't assign myself)

**Comment by agentpoyo** [comment]
- [ ] When I run `cnf-testsuite cert essential`, I should only see the essential tests run.
- [ ] I can see a screenshot of the output here of only essential tests

**Comment by agentpoyo** [comment]
![essentials_only](https://github.com/cnti-testcatalog/testsuite/assets/14348948/7cb1905a-13b5-411a-b6fc-796e1a3c9f1a)

**Comment by kosstennbl** [comment]
Seems that issue can be resolved, https://github.com/cnti-testcatalog/testsuite/pull/2012
