### ISSUE TITLE
[MAINTENANCE] Add helm_install_namespace to all sample cnfs for spec tests

### ISSUE THREAD

**Issue by martin-mat** [cnti-testcatalog/testsuite#2039]
The standard way to test CNF using cnf-testsuite is with deployment to non-default namespace. Reflect this in all spec tests (sample-cnfs/*) and include helm_install_namespace to all sample CNFs.

#2030

**Comment by barmull** [comment]
Used different approach. If it is not specified namespace in yaml file through the variable helm_install_namespace, the cnf will be installed into new created namespace cnf-default (not into default namespace).
