### ISSUE TITLE
[BUG] Equinix systems were shutdown unexpectedly

### ISSUE THREAD

**Issue by lixuna** [cnti-testcatalog/testsuite#2047]
**Describe the bug**
- Equinix systems were shutdown unexpectedly on Thur, May 16
- shutdown of GitHub runner machines

**Impact to project**
- unplanned shutdown of GitHub runners
- unable to test or merge PRs

Reference:
- https://github.com/cnti-testcatalog/testsuite/issues/2013

**Tasks**
- [x] backup of dev box off equinix
- [x] TBD

**Comment by taylor** [comment]
Systems were powered off but not deleted. All CI jobs hung or halted. Development in progress on the systems was killed (including pairing sessions).

They have been powdered back on, various things started and tested. CI with Github has been restarted, cancelled and rebooked, etc.

Any initial backup of the dev system in use has occurred. The remote dev system has not been migrated and will happen in another issue.

The CI runner migration continues in #2013.  CI runners do not need a backup. This issue can be closed as resolved.
