### ISSUE TITLE
[BUG] spec tests don't fail on unsuccessful cnf-setup

### ISSUE THREAD

**Issue by martin-mat** [cnti-testcatalog/testsuite#2083]
**Describe the bug**
In case that the cnf setup is unsuccessful on issues like:
- cluster-tools not ready after waiting for it (180)
- deployment of the cnf returns an error
- deployment of cnf not ready after waiting for it (180)
spec test ignore it and continue in test execution

see #2081 

**Expected behavior**
Spec test will fail as soon as mentioned errors occur

**Comment by martin-mat** [comment]
#1937

**Comment by kosstennbl** [comment]
#2114 Merged
