### ISSUE TITLE
[MAINTENACE] Clarify usage and behavior of testing multiple CNFs

### ISSUE THREAD

**Issue by martin-mat** [cnti-testcatalog/testsuite#2095]
Currently, it is possible to run cnf_setup multiple times for multiple CNFs/helm charts. When running tests then, tests are executed on each configured CNFs.
Clarify whether this is a supported feature. Currently, there is no documentation nor tests of this behavior.
If this should be supported behavior, address those aspects:
1. Add this to documentation
2. Add spec test(s) to verify expected functionality
3. Fix behavior of generating result yaml files. Currnently, just one yaml file is being generated; results of particular test are overwritten, and it records result only of the latest CNF. Which if obviously not expected behavior. Right behavior needs to be figured out and implemented.

If this is not supported usage, don't allow to call cnf_setup multiple times.

**Comment by martin-mat** [comment]
#2090

**Comment by martin-mat** [comment]
My input for the discussion/decision:

I propose not to have support for this. Reasons:
- The value of this feature is very low: The same results can be obtained by calling setup/test/cleanup in series with almost no duration difference.
- That feature creates confusions by usage by mistake. Users sometimes call multiple cnf_setup with different CNFs and then they are confused by results.
- That feature would require resources for documentation, testing and maintenance. That resources can be used better.
- Let's keep things simple.

**Comment by Smitholi67** [comment]
+1 for not supporting - let us keep it simple.

**Comment by kosstennbl** [comment]
So, for resolution of this issue:

1. Forbid installation of CNF if another CNF is already installed.
2. Resolve issue with usage of multiple CNF installation in spec tests:
    * These spec tests are not needed anymore and are removed as part of another issue
    * Use helm install/uninstall for auxiliary CNFs (can be complicated)
    * Change directory for installation of auxiliary CNFs to prevent blockage and unnecessary test runs.
