### ISSUE TITLE
[MAINTENANCE] Remove AIRGAP mode from code

### ISSUE THREAD

**Issue by kosstennbl** [cnti-testcatalog/testsuite#2104]
Few months ago from now on community meeting it was decided to stop support for AirGap mode. At that time - contributors and maintainers didn't have time to remove all the mentions of this mode of installation and operation from the code.

Currently, existing code around AirGap confuses new members of the community (#2099) and heavily obstructs some other parts of the code. (#2036)

I think that all code and documentation mentioning AirGap mode should be removed, if some of functionality would still be needed - it should be moved under other modules.

**Comment by martin-mat** [comment]
#1160
