### ISSUE TITLE
[Feature] Join installation modes HelmChart and HelmDirectory

### ISSUE THREAD

**Issue by kosstennbl** [cnti-testcatalog/testsuite#2106]
For Helm installation - we have 2 installation methods: HelmChart and HelmDirectory. Main difference between them is that HelmChart requires chart name, whereas HelmDirectory will try to find the chart in provided directory. That brings confusion and duplicity to the code of Testsuite.

I think, that these two methods should be joined into one "Helm" installation method, which would combine functionality of both.
Operation of that mode should depend on type of provided file in argument: 
1.  Chart name - pull and use
2.  Chart directory - find and use
3.  Tar archive - untar, find and use
Different cli argument names could be used, but for code - these methods should be equal, just with different types of preprocessing.

**Comment by svteb** [comment]
@kosstennbl is this still relevant?

**Comment by kosstennbl** [comment]
No, was done as a part of new installation method epic
