### ISSUE TITLE
[MAINTENANCE] update stable/envoy

### ISSUE THREAD

**Issue by kosstennbl** [cnti-testcatalog/testsuite#2116]
It seems that current version of envoy helm chart is being pulled from https://cncf.gitlab.io/stable as stable/envoy.
Kubernetes have deprecated some apis in version 1.25 (https://kubernetes.io/blog/2022/08/04/upcoming-changes-in-kubernetes-1-25/)

It seems that helm installation fails due to usage of some deprecated and unsupported API, `helm install envoy stable/envoy` gives this error: `Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: resource mapping not found for name: "envoy" namespace: "" from "": no matches for kind "PodDisruptionBudget" in version "policy/v1beta1"`, you can see template for pod PodDisruptionBudget in likely [source](https://github.com/helm/charts/blob/master/stable/envoy/templates/poddisruptionbudget.yaml)

Solution: update envoy version in the https://cncf.gitlab.io/stable repository. It seems that previous source was helm repo (https://github.com/helm/charts/blob/master/stable/envoy), but it's now deprecated. Some community chart should be tested and taken or other solution is needed.

**Comment by horecoli** [comment]
Update/upgrade of envoy was already tried to solve in past -> https://github.com/cnti-testcatalog/testsuite/issues/1938

**Comment by kosstennbl** [comment]
Sadly, #1938 doesn't have any proposals for the upgrade process itself. We have few options:

1. Somehow get access to CNCF gitlab and update the chart there
2. Change installation method to HelmDirectory and keep the updated version of chart in our testsuite repo
3. Upload the updated chart to some other helm repo, and pull it from there (or use some existing one).

**Comment by horecoli** [comment]
I would say #2 is good option for us and we will have some "freezed" version under our control inside our repository. Anyway we have same solution also in some other examples.
