### ISSUE TITLE
[MAINTENANCE] Delete or redesign of CNF configuration

### ISSUE THREAD

**Issue by barmull** [cnti-testcatalog/testsuite#2123]
Summary:
We need to evaluate the following three sample CNFs, which are currently not used in tests, are necessary to keep in the repository:

- sample-coredns-cnf2
- sample-coredns-cnf3
- sample-coredns-cnf4

Suggestions:

1.  DELETION of samples
2.  If deletion is not appropriate, we need to consider redesigning the cnf-testsuite.yaml file, focusing on the helm_install_namespace parameter.
- Consider if the helm_install_namespace parameter is necessary
- If the parameter is necessary, propose changing its value from cnfspace[1-4] to more descriptive name such as cnf-coredns[1-4] or cnf-default[1-4]

**Comment by martin-mat** [comment]
duplicate to #2073
