### ISSUE TITLE
Testsuite 1.3.2 deploys CNF into the default namespace even when helm_install_namespace is set

### ISSUE THREAD

**Issue by sysarch-repo** [cnti-testcatalog/testsuite#2146]
**Describe the bug**
After upgrade to 1.3.2 the CNF is deployed into the default namespace even when helm_install_namespace is set.

**To Reproduce**

1. Install 1.3.2
2. Use the following settings in cnf-testsuite.yml

Note, Helm package is used with the parameter helm_directory as per https://github.com/cnti-testcatalog/testsuite/discussions/2041
```
helm_directory: dns-24.03.0.tgz
helm_install_namespace: dns-system
release_name: dns
```

6. See the CNF deployed in the default namespace

**Expected behavior**
The parameter helm_install_namespace shall be respected if set (just like with 1.3.1).

**Device (please complete the following information):**
```
[ec2-user@ip-10-0-110-88 ~]$ uname -a
Linux ip-10-0-110-88.ec2.internal 5.10.223-212.873.amzn2.x86_64 #1 SMP Wed Aug 7 16:53:32 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

**How will this be tested? aka Acceptance Criteria (optional)**

**Additional context**

**Comment by martin-mat** [comment]
I guess this is addressed by already merged #2127 so a next release should contain the fix. @barmull to check.

**Comment by barmull** [comment]
I checked it on current main branch, and everything works as expected. If variable helm_install_namespace is not set , then cnf is installed into cnf-default. If variable is set, cnf is installed into helm_install_namespace value.

**Comment by sysarch-repo** [comment]
Thanks! I am closing the ticket.

**Comment by martin-mat** [comment]
@sysarch-repo 
https://github.com/cnti-testcatalog/testsuite/releases/tag/v1.3.3
should work.
