### ISSUE TITLE
[Feature] CNF Installation (8), Transition to new installation method.

### ISSUE THREAD

**Issue by kosstennbl** [cnti-testcatalog/testsuite#2169]
Final step for introduction of new installation method and support for multiple deployment installation.

A lot should be done in according PR(s), here's generalized list of this:

- [x] Removal of old installation tasks.
- [x] Adaptation of CI for the change above.
- [x] Removal of setup specs that wouldn't be valid anymore, rewriting task names for new and remaining old ones.
- [x] Cleanup through the whole testcatalog code, everything that wouldn't be used anymore should be removed to avoid confusion and make code cleaner and more understandable.
- [x] Removal of source_cnf_dir dynamic parameter from config. "reasonable_image_size" test should be redesigned to use cnfs/temp_files
- [x] Removal of destination_cnf_dir dynamic parameter from config. Multiple tests should be redesigned, some should be adapted to work with multiple deployments, others - to use temp_files dir.
- [x] Removal of install_method dynamic parameter from config. It isn't used in tests, cnf_manager methods should be removed or adapted.
- [x] Adapt config updater and config v2 for removal of dynamic parameters. remove unnecessary methods
- [x] Redesign every usage of get_deployment_param to work with multiple deployments and deployment types.
- [x] Rename "cnfs" directory to "installed_cnf_files" directory
- [x] Change all paths that are no longer valid due to new directory name

Possibly more tasks would be added

**Comment by svteb** [comment]
Resolved in #2171 .
