### ISSUE TITLE
Does CNTI supports the testing for an existing or deployed CNF(s)?

### ISSUE THREAD

**Issue by adityaSiso** [cnti-testcatalog/testsuite#2173]
I was wondering if we could test a deployed CNF(s) via `cnf-testsuite`. We've access to the cluster where the CNF(s) are running but not the helm directory, charts, and manifest files.

Do we have any workaround to test those CNF(s) without requiring the charts and other things?

**Comment by svteb** [comment]
I'm afraid this is currently not possible as we specifically use the `./cnf-testsuite cnf_setup <path-to-your-config>` and the `cnf-testsuite.yml` file to keep track of the resources that should be tested. Additionally a feature request like that would be very hard to implement currently.
