### ISSUE TITLE
[Feature] EPIC: Add emojis to tests that are missing emojis

### ISSUE THREAD

**Issue by lixuna** [cnti-testcatalog/testsuite#334]
**Problem:**
- some of the workload tests are missing emojis to represent the test

**Solution:**
- find emojis that would visually represent the cloud native conformance test
- ie. using the emojis 📦 💻 🐷 📈 to represent the test called ``cnf-conformance chaos_cpu_hog``

**Ways to help:**
- create a new [Feature Request issue](https://github.com/cncf/cnf-conformance/issues/new?assignees=&labels=enhancement&template=feature-request.md&title=%5BFeature%5D) with the suggested emojis that you would like to see in each test 
- [fork the code](https://github.com/cncf/cnf-conformance/fork), update the test to add emojis, reference the issue the commit, [create a pull request](https://github.com/cncf/cnf-conformance/compare)

**List of tests that need emojis**
- Issues marked with [emoji label](https://github.com/cncf/cnf-testsuite/labels/emoji) 

**How will this be tested**
- run workload tests
- I would expect to see emojis to tests in the test results

**Comment by taylor** [comment]
@lixuna the workload test results for `main` branch as of 2021-05-05 at 22:02 UTC (5:02PM CT)

![cnf test suite pass and fail results for a test run by Taylor](https://user-images.githubusercontent.com/26697/117220101-2f187e00-adcc-11eb-8ec1-fc344a65c5e2.png)

**Comment by taylor** [comment]
https://github.com/cncf/cnf-testsuite/pull/758 adds some for helm tests

**Comment by lixuna** [comment]
Note: Hardcoded emojis have been replaced with variables in #336

**Comment by lixuna** [comment]
The workload test results can be viewed in this video recording
https://asciinema.org/a/DUI1XgA45N4OJ8sKZQ2hinCfn

We'll create separate issues (one GitHub issue per test) to add an emoji set to a test, and tag the new issues as "good first issues"

**Comment by lixuna** [comment]
closing issue as stale - can be reopened if prioritized by community
