### ISSUE TITLE
[Feature] Replace hardcoded timeouts with variables

### ISSUE THREAD

**Issue by lixuna** [cnti-testcatalog/testsuite#335]
**Problem:** 
- some of the tests contain hardcoded timeouts, it would be nice to have constants that timeout vs putting the number in the code
- ie. [wait_count = 60](https://github.com/cncf/cnf-testsuite/blob/17f4bd9abed012fced408fe512ece5e0364b064f/src/tasks/resilience.cr) 

**Possible solution:**
- Replace hardcoded timeouts with variables

**List of tests to replace hardcoded timeouts**
- tbd, need to add to issue 
- [ ] [src/tasks/litmus_setup.cr](https://github.com/cncf/cnf-testsuite/blob/fc29a3b3177cc006ffe1672c7b352567b8ebb4ed/src/tasks/litmus_setup.cr)
- [ ] [src/tasks/chaos_mesh_setup.cr](https://github.com/cncf/cnf-testsuite/blob/130c50caf83d4b6c804e9f933a06b8a1116472df/src/tasks/chaos_mesh_setup.cr)
- [ ] [src/tasks/workload/resilience.cr](https://github.com/cncf/cnf-testsuite/blob/fc29a3b3177cc006ffe1672c7b352567b8ebb4ed/src/tasks/workload/resilience.cr)
- [ ] [src/tasks/workload/microservice.cr](https://github.com/cncf/cnf-testsuite/blob/54462ac22221ab25b99833e803eec6a8bb6ebff4/src/tasks/workload/microservice.cr)
- [ ] [spec/workload/microservice_spec.cr](https://github.com/cncf/cnf-testsuite/blob/5247c77b203fbeccb47c7e8a0adaf827c52f7b4f/spec/workload/microservice_spec.cr)
- [ ] [spec/utils/utils_spec.cr](https://github.com/cncf/cnf-testsuite/blob/5247c77b203fbeccb47c7e8a0adaf827c52f7b4f/spec/utils/utils_spec.cr)
- [ ] [spec/workload/statelessness_spec.cr](https://github.com/cncf/cnf-testsuite/blob/5247c77b203fbeccb47c7e8a0adaf827c52f7b4f/spec/workload/statelessness_spec.cr)
- [ ] [spec/workload/resilience/network_chaos_spec.cr](https://github.com/cncf/cnf-testsuite/blob/5247c77b203fbeccb47c7e8a0adaf827c52f7b4f/spec/workload/resilience/network_chaos_spec.cr)
- [ ] [spec/utils/cnf_manager_spec.cr](https://github.com/cncf/cnf-testsuite/blob/5247c77b203fbeccb47c7e8a0adaf827c52f7b4f/spec/utils/cnf_manager_spec.cr)
- [ ] [spec/workload/installability_spec.cr](https://github.com/cncf/cnf-testsuite/blob/5247c77b203fbeccb47c7e8a0adaf827c52f7b4f/spec/workload/installability_spec.cr)

**How will this be tested**

- [ ] Create a modified CNF that will exceed the time limits specified for the specific tests, 
- [ ] Run workload tests 
- [ ] I would expect the tests in question to fail if the wait_count is exceeded 
- [ ] I would expect the tests in question to pass if the test finishes before the wait_count limit

**Comment by taylor** [comment]
@williscool please link to an example of a hardcoded timeout

**Comment by williscool** [comment]
boom 

https://github.com/cncf/cnf-conformance/blob/17f4bd9abed012fced408fe512ece5e0364b064f/src/tasks/resilience.cr#L186

**Comment by taylor** [comment]
and https://github.com/cncf/cnf-conformance/blob/17f4bd9abed012fced408fe512ece5e0364b064f/src/tasks/resilience.cr#L224

**Comment by lixuna** [comment]
Hello, @kosstennbl is this issue in progress?

> [kosstennbl](https://github.com/kosstennbl) added a commit to kosstennbl/cnf-testsuite that referenced this issue [on Jan 31](https://github.com/cnti-testcatalog/testsuite/issues/335#ref-commit-54bbb52)
@kosstennbl
[WIP:](https://github.com/kosstennbl/cnf-testsuite/commit/54bbb526a1ad4af620ba345017617929c0ccb7dc) https://github.com/cnti-testcatalog/testsuite/issues/335[: Change timeouts to constant variables](https://github.com/kosstennbl/cnf-testsuite/commit/54bbb526a1ad4af620ba345017617929c0ccb7dc) …
[54bbb52](https://github.com/kosstennbl/cnf-testsuite/commit/54bbb526a1ad4af620ba345017617929c0ccb7dc)
Use constants with meaningfull names for defining timeouts
for different tasks and waiters. Where possible - unify
multiple values under one variable.

Signed-off-by: Konstantin Yarovoy <konstantin.yarovoy@tietoevry.com>

**Comment by kosstennbl** [comment]
@lixuna 
Hi, yes, I've left it behind for several months, but this week I've started again and It will probably be ready for review by Friday-Monday
