### ISSUE TITLE
[BUG] Any test should be skipped if the dependency tools for that test are not installed 

### ISSUE THREAD

**Issue by wavell** [cnti-testcatalog/testsuite#655]
**Describe the bug**
Any test should be skipped if the dependency tools for that test are not installed 

To Reproduce

Install a CNF with dependencies
Run test: e.g. reasonable_image_size
If the dependency is not installed and cannot be installed then the test fails.
Expected behavior
The test should be ignored if the dependency is not installed.

**Comment by lixuna** [comment]
@wavell @HashNuke @agentpoyo Is this issue still relevant?
