### ISSUE TITLE
[Feature] Start timer after image has been pulled

### ISSUE THREAD

**Issue by sishbi** [cnti-testcatalog/testsuite#691]
**Is your feature request related to a problem? Please describe.**
For tests that expect a pod to start within a short time the test will fail if the image takes a long time to be pulled

**Describe the solution you'd like**
Start the timer after the image has been pulled

**Describe alternatives you've considered**
No alternatives considered, current behaviour is not to wait until pull complete

**Additional context**
Need to track events for a pod until Pulled event occurs and then start timer
Need to have a time limit for pulling to avoid test hanging indefinitely
Related to https://github.com/cncf/cnf-conformance/pull/683/commits/a5f29ae6f067c2ef7c4a1bf7e6db0e507e931c01

**Comment by lixuna** [comment]
closing issue as stale - can be reopened if prioritized by community
