### ISSUE TITLE
[EPIC] Address whether SKIPPED tests (Soft failures & Crystal failures) should be inclusive or exclusive of the Total Score. (Handling of N/A tests)

### ISSUE THREAD

**Issue by denverwilliams** [cnti-testcatalog/testsuite#707]
**Describe the bug**
Address whether SKIPPED tests (Soft failures & Crystal failures) should be inclusive or exclusive of the Total Score. (Handling of N/A tests).

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device (please complete the following information):**
 - OS [e.g. Linux, iOS, Windows, Android]
 - Distro [e.g. Ubuntu]
 - Version [e.g. 18.04]
 - Architecture [e.g. x86, arm]

**Additional context**

---

NOTE: you can enable higher logging level output via the command line or env var. to help with debugging

```
# cmd line
./cnf-conformance -l debug test

# make sure to use -- if running from source
crystal src/cnf-conformance.cr -- -l debug test 

# env var
LOGLEVEL=DEBUG ./cnf-conformance test
```

Also setting the verbose option for many tasks will add extra output to help with debugging

```
crystal src/cnf-conformance.cr test_name verbose
```

Check [usage documentation](https://github.com/cncf/cnf-conformance/blob/master/USAGE.md) for more info about invoking commands and loggin

**Comment by wavell** [comment]
Planning
https://hackmd.io/6lp0LeL5S06FBr32PVYy1w @taylor

**Comment by wavell** [comment]
We should identify each test that needs skipped/na functionality and create a new ticket for them

**Comment by lixuna** [comment]
For the CNF Certification, let's decide which tests will be included in v1 and determine if we still need to handle tests that are likely to be skipped in that group.
