### ISSUE TITLE
[Feature] Install tool directory to the ~/.cnf-testsuite directory and add it to the PATH

### ISSUE THREAD

**Issue by taylor** [cnti-testcatalog/testsuite#747]
**Is your feature request related to a problem? Please describe.**
The tool directory is added to your current path.  The user could be anywhere.  How will the binary find the tools if you go to a new directory? How do they cleanup later?

**Describe the solution you'd like**
Install the tools to the cnf-testsuite folder (~/.cnf-testsuite).
Update the cnf-testsuite to use the tools from the new path.
Add the tool folder to the user PATH during setup (`cnf-testsuite setup`)

**Describe alternatives you've considered**
n/a

**How will this be tested? aka Acceptance Criteria (optional) **

(optional: unnecessary for things like some version bumps etc.)

Once this issue is addressed how will the fix be verified?

The tools folder will be in ~/.cnf-testsuite

**Additional context**
![image](https://user-images.githubusercontent.com/26697/116471793-b731dd00-a83a-11eb-9e3f-d4f7568f37d3.png)

**Comment by lixuna** [comment]
@taylor is this issue still relevant for CNTI?
