### ISSUE TITLE
[Feature] Check if image has been scanned

### ISSUE THREAD

**Issue by wvwatson** [cnti-testcatalog/testsuite#755]
**Is your feature request related to a problem? Please describe.**
Before a CNF image is downloaded, it should have a security scan run against it.

**Describe the solution you'd like**
Check to see if the image is hosted in a local registry that supports scanning, and check to see if the image has been scanned.

**Describe alternatives you've considered**
Check to see if the CNF is hosted on a public registry that automatically scans the image.

**How will this be tested? aka Acceptance Criteria (optional) **

Ping the registry's API for scanning data based on the image that will be downloaded

**Additional context**
https://editor.swagger.io/?url=https://raw.githubusercontent.com/goharbor/harbor/master/api/v2.0/swagger.yaml

**Comment by lixuna** [comment]
@wavell  can this issue be closed?

**Comment by kosstennbl** [comment]
IMO, that is out of responsibilities of testsuite. User creates CNF config with selected images, if additional security scanning is needed - it should be done separately.
