### ISSUE TITLE
[Feature] Add "help" or "usage" if an argument is passed that requires more arguments.

### ISSUE THREAD

**Issue by agentpoyo** [cnti-testcatalog/testsuite#756]
**Describe the solution you'd like**
When passing an argument after `./cnf-testsuite cnf_setup`, cnf_setup requires more arguments, if nothing passed on command line, cnf-testsuite should display usage or help based on that argument.

For instance, `cnf_setup` requires `cnf-config=./path/to/config` or `cnf-path=./path/to/dir` so if this requirement is not met, it should print out usage help. 

**Describe alternatives you've considered**
None

**Additional context**
This should apply to any arguments that require more arguments passed.

**Comment by lixuna** [comment]
@agentpoyo can this issue be closed?
