### ISSUE TITLE
[Feature] generate_config should provide output if not additional argument is given

### ISSUE THREAD

**Issue by agentpoyo** [cnti-testcatalog/testsuite#757]
**Describe the solution you'd like**
When passing `./cnf-testsuite generate_config`, if `config-src=` is not passed and or `output-file=`, it should print out help and usage of the required options needed to perform the generate_config.

Ref Issues: https://github.com/cncf/cnf-testsuite/issues/756

**How will this be tested? aka Acceptance Criteria (optional) **
When a user passes `./cnf-testsuite generate_config` with no additional arguments, it will print out usage of available commands or options.

**Comment by lixuna** [comment]
@agentpoyo can this issue be closed?
