### ISSUE TITLE
[Feature] cnf-testsuite generate_config should prompt to overwrite specified output-file YML config if the file exists already

### ISSUE THREAD

**Issue by agentpoyo** [cnti-testcatalog/testsuite#762]
**Is your feature request related to a problem? Please describe.**
When generating a cnf-testsuite.yml config file using generate_config option, it will not overwrite the existing file if it exists in the specified output-file= argument. This can lead to a new generate config file that is not valid for testing.

**Describe the solution you'd like**
cnf-testsuite should prompt if you use the same config-file to overwrite or keep, exit immediately if you do not want to overwrite so you know to use a different output file name for your config.

**Comment by lixuna** [comment]
@agentpoyo can this issue be closed?
