### ISSUE TITLE
[Feature] Create config.yml automatically when setup is ran unless it already exists, and do not include in the git repo

### ISSUE THREAD

**Issue by taylor** [cnti-testcatalog/testsuite#764]
**Is your feature request related to a problem? Please describe.**
The config.yml is tracked in the git repo. This means local changes for a developer's environment need to be dealt with for every commit. It also means local developer changes could accidentally make it into a production binary release.

**Describe the solution you'd like**

1. Stop tracking config.yml in the git repo
2. When the internal setup action runs (via `setup` or automatically when cnf_setup or a test command calls it) create a config.yml unless one already exists (in which case it should be used).

**Describe alternatives you've considered**

- Stop tracking but don't generate automatically. 
- Have a config.yml.example for download
- Have config.yml documented only

**How will this be tested? aka Acceptance Criteria (optional) **

(optional: unnecessary for things like some version bumps etc.)

Once this issue is addressed how will the fix be verified?

Clone of the repo should not show config.yml.

Running `cnf-testsuite setup` should create a config.yml file.

**Additional context**

Idea for implementation:
- create a config-global.yml (not visible in 
- override global with data from config.yml data

**Comment by lixuna** [comment]
@taylor  can this issue be closed?
