### ISSUE TITLE
[Feature] Pull down helm binary for Mac OS X clients during `setup`

### ISSUE THREAD

**Issue by agentpoyo** [cnti-testcatalog/testsuite#800]
**Is your feature request related to a problem? Please describe.**
`cnf-testsuite setup` currently will pull down amd64 binary (Intel) for helm if not detected locally and cnf-testsuite will use if missing.

**Describe the solution you'd like**
We should do the same detection of OS and check if helm is available or not, if not found it  it will pull down the helm binary for Mac OS X (darwin) users to satisfy requirements to run cnf-testsuite.

**How will this be tested? aka Acceptance Criteria (optional) **

Mac OS X is only supported from Source Install.

- [ ] Follow the source install steps to get the binary running.
- [ ] Run `cnf-testsuite setup` and see that the helm that is not installed or detected locally on the client pulls down the binary into the tools/ directory for use by cnf-testsuite.

Once this issue is addressed how will the fix be verified?

By running the Acceptance Criteria above.

**Comment by lixuna** [comment]
@agentpoyo can this issue be closed?
