### ISSUE TITLE
[BUG] Running `airgapped` option to path that might not exist and results with no tarball creation

### ISSUE THREAD

**Issue by agentpoyo** [cnti-testcatalog/testsuite#803]
**Describe the bug**
This might be a feature but seems more like a bug. When running `cnf-testsuite airgapped output-file=/mypath/airgapped.tar.gz`, where /mypath doesn't exist, cnf-testsuite will act like it's creating the tarball and state it was successful but yet there is no tarball available since /mypath directory does not exist.

**To Reproduce**

1. Install cnf-testsuite
2. Make sure there is no directory called `mydir` in your current $(pwd) you are running and specifying to place the tarball.
3. Run the airgapped option `cnf-testsuite airgapped output-file=./mydir/airgapped.tar.gz`
4. cnf-testsuite will report the airgap setup is complete but since there is no ./mydir, there will be no tarball available.

See screenshot as debug has output where tar has errors but the test suite still claims success.

**Expected behavior**
Two options:
1. cnf-testsuite will make the directory if non-existent and if the user running has permissions to mkdir or;
2. cnf-testsuite errors out, indicating the path used does not exist and the user needs to create or use a valid PATH

**Screenshots**
![image](https://user-images.githubusercontent.com/14348948/120742215-221aa780-c4bc-11eb-817f-8ab1cab4d7bc.png)

**Comment by lixuna** [comment]
Closing as CNTI Test Catalog group is discussing removing airgapped support
