### ISSUE TITLE
[Feature] CNF Setup should support dependent helm charts in airgap mode

### ISSUE THREAD

**Issue by wavell** [cnti-testcatalog/testsuite#816]
**Is your feature request related to a problem? Please describe.**
CNF Setup does not support dependent helm charts in air gap mode

**Describe the solution you'd like**
CNF Setup should support dependent helm charts in air gap mode by allowing the user to supply a list of images in the cnf-testsuite.yml

**Comment by lixuna** [comment]
Closing as CNTI Test Catalog group is discussing removing airgapped support
