### ISSUE TITLE
[Feature] Manifest Directory should be treated as a first class citizen

### ISSUE THREAD

**Issue by wavell** [cnti-testcatalog/testsuite#817]
**Is your feature request related to a problem? Please describe.**
Manifest Directory such as the k8s_non_helm example should mark a test as N/A or skipped if the test is not applicable when running the workload test

**Describe the solution you'd like**
Manifest Directory should be treated as a first class citizen

**Comment by lixuna** [comment]
closing issue as stale - can be reopened if prioritized by community
