### ISSUE TITLE
[Feature] Suppress stdout messages that are not actual ERRORS during airgap `cnf_setup` commands.

### ISSUE THREAD

**Issue by agentpoyo** [cnti-testcatalog/testsuite#822]
**Is your feature request related to a problem? Please describe.**

When running the following command to cnf_setup in airgapped mode, it displays `ls: cannot access` messages that are not yet relevant:

`./cnf-testsuite cnf_setup cnf-config=./example-cnfs/coredns/cnf-testsuite.yml airgapped=/tmp/airgapped.tar.gz`

![image](https://user-images.githubusercontent.com/14348948/123323348-fd35b500-d4fa-11eb-892b-1294dfebb25a.png)

**Describe the solution you'd like**
Stdout from commands should be oppressed in log_level ERROR mode, only displaying if it's a real error on the backend.

**Comment by lixuna** [comment]
Closing as CNTI Test Catalog group is discussing removing airgapped support
