### ISSUE TITLE
[BUG] `cnf_setup` when using `airgapped=filename.tar.gz` creates a cnf-testsuite.yml in `pwd` that then errors

### ISSUE THREAD

**Issue by agentpoyo** [cnti-testcatalog/testsuite#823]
**Describe the bug**
`./cnf-testsuite cnf_setup cnf-config=/sample-cnf/cnf-testsuite.yml airgapped=/tmp/airgapped.tar.gz` is creating a new cnf-testsuite.yml in your `pwd`.

If you run the same command again to add a new CNF to your existing airgapped.tar.gz for offline mode, it errors with:

```
E, [2021-06-24 17:15:11 -05:00 #240342] ERROR -- cnf-testsuite: ./cnf-testsuite.yml already exists
```

**To Reproduce**

1. Create an airgapped tarball using `setup`
2. Now add your CNF to the airgapped tarball you just created with the command (this uses the sample coredns available):
`./cnf-testsuite cnf_setup cnf-config=./sample-cnfs/sample_coredns/cnf-testsuite.yml airgapped=/tmp/airgapped.tar.gz`
3. Run the next step in setting up the CNF on your airgapped cluster:
`./cnf-testsuite cnf_setup cnf-config=./sample-cnfs/sample_coredns/cnf-testsuite.yml input-file=/tmp/airgapped.tar.gz`
4. Run your workload or other tests.
5. Now add another CNF to your existing airgapped tarball:
`./cnf-testsuite cnf_setup cnf-config=./example-cnfs/coredns/cnf-testsuite.yml airgapped=/tmp/airgapped.tar.gz`
6. See error:
![image](https://user-images.githubusercontent.com/14348948/123340197-74764380-d511-11eb-9135-2c11c12fe108.png)

**Expected behavior**
cnf-testsuite should not create a cnf-testsuite.yml in your current working directory, only in your cnfs/ directory where it actually reads and runs the tests using the cnf-testsuite.yml file created.

**Device (please complete the following information):**

- OS = Linux
- Distro = Fedora
- Version = 32
- Architecture = x86

**Comment by lixuna** [comment]
Closing as CNTI Test Catalog group is discussing removing airgapped support
