### ISSUE TITLE
[Feature] Tests with timeout wait conditions or that are long running should have a status bar indicator

### ISSUE THREAD

**Issue by agentpoyo** [cnti-testcatalog/testsuite#859]
**Is your feature request related to a problem? Please describe.**
Long running tests should show some type of indication the test is still running. A good example of where this occurs is pointed out in this bug: https://github.com/cncf/cnf-testsuite/issues/857

**Describe the solution you'd like**
Create some type of status bar or indicator the testsuite is still running, minute+ long pauses without any output might give the impression the testsuite is failing or paused, etc.

**Describe alternatives you've considered**
Status indicator animated image next to the test that's running.

**Comment by lixuna** [comment]
@agentpoyo can this issue be closed?
