### ISSUE TITLE
[Feature] Adding missing ⏭️ for SKIPPED test output on command line and update SKIPPED with :x: emoji

### ISSUE THREAD

**Issue by agentpoyo** [cnti-testcatalog/testsuite#878]
**Describe the solution you'd like**
There are SKIPPED tests missing the default ⏭️ emoji or have the :x: during cnf-testsuite output on the command line. All tests that have the SKIPPED option should include this emoji to keep the output consistent.

**Additional context**
These are the current tests missing or have the wrong emoji, ex. :x: instead of ⏭️ from a quick search and find:

```
src/tasks/workload/installability.cr:  "SKIPPED: Helm Deploy"
src/tasks/workload/configuration_lifecycle.cr:  "✖️  SKIPPED: immutable configmaps..."
src/tasks/platform/observability.cr:  "SKIPPED: Kube State Metrics"
src/tasks/platform/observability.cr:  "SKIPPED: Node Exporter"
src/tasks/platform/observability.cr:  "SKIPPED: Prometheus Adapter"
src/tasks/platform/observability.cr:  "SKIPPED: Metrics Server"
src/tasks/platform/platform.cr:  "SKIPPED: ClusterAPI Enabled"
src/tasks/platform/resilience.cr:  "SKIPPED: Node Failure"
```

**Comment by SriSatyaT** [comment]
@agentpoyo I want to work on this issue.

**Comment by agentpoyo** [comment]
> @agentpoyo I want to work on this issue.

Hello @SriSatyaT 

Welcome to the CNF Test Suite! and thanks for showing interest in contributing. Here is the link to the [Contributing Guide](https://github.com/cncf/cnf-testsuite/issues/CONTRIBUTING.md).

If you have any questions, please feel free to tag @lixuna @taylor @wavell @denverwilliams @agentpoyo @HashNuke and/or @williscool.

**Comment by SriSatyaT** [comment]
> > @agentpoyo I want to work on this issue.
> 
> Hello @SriSatyaT
> 
> Welcome to the CNF Test Suite! and thanks for showing interest in contributing. Here is the link to the [Contributing Guide](https://github.com/cncf/cnf-testsuite/issues/CONTRIBUTING.md).
> 
> If you have any questions, please feel free to tag @lixuna @taylor @wavell @denverwilliams @agentpoyo @HashNuke and/or @williscool.

I tried to run the command "curl -s https://raw.githubusercontent.com/cncf/cnf-testsuite/main/curl_install.sh | bash" but there was no respond like any message in prompt I waited till 20 minutes and terminated and got this message. Should I proceed to next step or should I run this again.
![Command Prompt 14-09-2021 21_21_20](https://user-images.githubusercontent.com/78905067/133292682-fea8c01e-870b-414b-afca-ccf9ee42f7a6.png)

**Comment by agentpoyo** [comment]
> > > @agentpoyo I want to work on this issue.
> > 
> > 
> > Hello @SriSatyaT
> > Welcome to the CNF Test Suite! and thanks for showing interest in contributing. Here is the link to the [Contributing Guide](https://github.com/cncf/cnf-testsuite/issues/CONTRIBUTING.md).
> > If you have any questions, please feel free to tag @lixuna @taylor @wavell @denverwilliams @agentpoyo @HashNuke and/or @williscool.
> 
> I tried to run the command "curl -s https://raw.githubusercontent.com/cncf/cnf-testsuite/main/curl_install.sh | bash" but there was no respond like any message in prompt I waited till 20 minutes and terminated and got this message. Should I proceed to next step or should I run this again.


Hello @SriSatyaT ,

The cnf-testsuite doesn't run natively on the Windows Command Line. You can setup WSL (Windows Subsystem for Linux) to install the suite onto. But you'll need a `bash` prompt in order to successfully install the test suite.

Cheers,

-ap

**Comment by Qarthak** [comment]
@agentpoyo I want to work on this issue

**Comment by HashNuke** [comment]
@Qarthak Hello Sarthak. Feel free to contribute by sending a PR.

If you haven’t tried/used the project before checkout the readme and see if that helps you setup the project. Let us know if you get stuck and we can help you get started.

You can ping any one of us mentioned in the previous comments for help.

**Comment by agentpoyo** [comment]
@Qarthak @HashNuke 

Definitely review the code but I think this might of been addressed already during another issue feature where we cleaned up and reorganized the console output. But do feel free to review to see if any proper emoji handlers are missing or need correction. Thanks.

**Comment by agentpoyo** [comment]
#### Acceptance Criteria

- [ ] Find or use existing K8s cluster
- [ ] Setup cnf-testsuite using pre-built binary if available with updates or checkout source code and follow source installation 
- [ ] Setup CNF using example or sample CNF's
- [ ] When I run the tests: 
    - Helm Deploy
    - immutable configmaps
    - Kube State Metrics"
    - Node Exporter"
    - Prometheus Adapter"
    - Metrics Server"
    - ClusterAPI Enabled"
    - Node Failure"
 I should see the SKIPPED emoji ⏭️ when the test is SKIPPED.
