### ISSUE TITLE
[BUG] Test suite should exit after helm pull failure

### ISSUE THREAD

**Issue by williscool** [cnti-testcatalog/testsuite#886]
**Describe the bug**

**To Reproduce**

```
william@MSI:/mnt/c/Users/william/unison-with-dropbox-symlinked-to-linux/vulk_stuff/cnf-testsuite$ ./cnf-testsuite cnf_setup cnf-config=./cnf-testsuite.yml; ~/my_confs/wsl-notification.sh
Successfully created directories for cnf-testsuite
cnf setup online mode
Helm pull error
mv: cannot move '/mnt/c/Users/william/unison-with-dropbox-symlinked-to-linux/vulk_stuff/cnf-testsuite/cnfs/coredns/exported_chart/coredns/templates' to '/mnt/c/Users/william/unison-with-dropbox-symlinked-to-linux/vulk_stuff/cnf-testsuite/cnfs/coredns/exported_chart/templates': Directory not empty

```

**Expected behavior**

The binary should not try to move anything if there is nothing to move (because of the helm pull failure)

**Screenshots**

![image](https://user-images.githubusercontent.com/394931/127094402-291e3a9b-27ac-4e95-bfcd-0b7562ba361f.png)

**Device (please complete the following information):**

- OS [e.g. Linux, iOS, Windows, Android] linux wsl
- Distro [e.g. Ubuntu]
- Version [e.g. 18.04]
- Architecture [e.g. x86, arm]

**How will this be tested? aka Acceptance Criteria (optional)**

(optional: unnecessary for things like spelling errors and such)

Once this issue is address how will the fix be verified?

**Additional context**

---

NOTE: you can enable higher logging level output via the command line or env var. to help with debugging

```
# cmd line
./cnf-testsuite -l debug test

# make sure to use -- if running from source
crystal src/cnf-testsuite.cr -- -l debug test

# env var
LOGLEVEL=DEBUG ./cnf-testsuite test
```

Also setting the verbose option for many tasks will add extra output to help with debugging

```
crystal src/cnf-testsuite.cr test_name verbose
```

Check [usage documentation](https://github.com/cncf/cnf-testsuite/blob/main/USAGE.md) for more info about invoking commands and logging

**Comment by lixuna** [comment]
@HashNuke @agentpoyo has this been completed? Can the issue be closed?

**Comment by lixuna** [comment]
closing issue as stale - can be reopened if prioritized by community
