### ISSUE TITLE
[Feature] Test for feature gates when checking support for immutable configmaps

### ISSUE THREAD

**Issue by HashNuke** [cnti-testcatalog/testsuite#905]
### Is your feature request related to a problem? Please describe.

In a few places in the test suite, the kubernetes version is being checked as being 1.19 or greater to use immutable configmaps. But as @williscool pointed out in a comment on PR #861, we should also be checking for feature gates to see if Immutable configmaps are supported.

According to [the Kubernetes docs on feature gates](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/),
* Immutable configmaps are available and enabled by default in 1.19 & 1.20, but are still behind a feature gate (translating to chances of being disabled).
* Immutable ConfigMaps are only generally available since 1.21.

### Describe the solution you'd like

To confirm availability of immutable configmaps, apart from checking for the Kubernetes version, ensure feature gate is also enabled.

### Describe alternatives you've considered
*None*

### How will this be tested? aka Acceptance Criteria (optional)
*None*

**Comment by lixuna** [comment]
@HashNuke Is still issue still relevant?
