### ISSUE TITLE
[BUG] Fix bug with reasonable_startup_time spec test.

### ISSUE THREAD

**Issue by denverwilliams** [cnti-testcatalog/testsuite#926]
**Describe the bug**
The envoy / slow startup time spec test is reporting a startup time of 1sec. Which is incorrect and causing intermittent CI failures.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device (please complete the following information):**

- OS [e.g. Linux, iOS, Windows, Android]
- Distro [e.g. Ubuntu]
- Version [e.g. 18.04]
- Architecture [e.g. x86, arm]

**How will this be tested? aka Acceptance Criteria (optional)**

(optional: unnecessary for things like spelling errors and such)

Once this issue is address how will the fix be verified?

**Additional context**

---

NOTE: you can enable higher logging level output via the command line or env var. to help with debugging

```
# cmd line
./cnf-testsuite -l debug test

# make sure to use -- if running from source
crystal src/cnf-testsuite.cr -- -l debug test

# env var
LOGLEVEL=DEBUG ./cnf-testsuite test
```

Also setting the verbose option for many tasks will add extra output to help with debugging

```
crystal src/cnf-testsuite.cr test_name verbose
```

Check [usage documentation](https://github.com/cncf/cnf-testsuite/blob/main/USAGE.md) for more info about invoking commands and logging

**Comment by taylor** [comment]
@denverwilliams review. may be invalid and fixed else where

**Comment by lixuna** [comment]
@denverwilliams @agentpoyo @HashNuke can this issue be closed?
