### ISSUE TITLE
[BUG] airgap should add the configured helm repo to use during tarball creation

### ISSUE THREAD

**Issue by agentpoyo** [cnti-testcatalog/testsuite#964]
**Describe the bug**
When running the airgap setup to create a tarball for offline airgap usage, it is not adding the configured helm repo defined if missing or not already listed as a helm repo.

**To Reproduce**

1. Remove your helm repos 
2. Follow the steps to create an airgap tarball
3. It should fail when it attempts to use helm to pull down anything necessary to create the offline tarball

**Expected behavior**
During airgap tarball, any helm repo configured for a CNF should be added if not already present.

**Comment by lixuna** [comment]
Closing as CNTI Test Catalog group is discussing removing airgapped support
