### ISSUE TITLE
[BUG] cnf_setup fails with a stacktrace when a Kubernetes cluster is not configured

### ISSUE THREAD

**Issue by HashNuke** [cnti-testcatalog/testsuite#985]
**Describe the bug**

When `cnf_setup` is run without a Kubernetes cluster configured, then the cnf_setup command results in a crash and displays the stacktrace.

![image](https://user-images.githubusercontent.com/84005/134780537-7c7f1124-aba8-4238-9ca9-1f7d54d4050f.png)

**To Reproduce**

```
unset KUBECONFIG
 ./cnf-testsuite cnf_setup cnf-config=./sample-cnfs/sample_nonroot/cnf-testsuite.yml
```

**Expected behavior**

Should display an error that a Kubernetes server is not accessible.

**Comment by lixuna** [comment]
hi @HashNuke is this issue still relevant for cnti?

**Comment by HashNuke** [comment]
Confirmed. This issue still exists. Screenshot below. Tagging for contributors.

![CleanShot 2024-03-04 at 18 29 15@2x](https://github.com/cnti-testcatalog/testsuite/assets/84005/ba6b3bff-8cae-48c4-b37f-dc4b3b0dd060)

**Comment by barmull** [comment]
I added method `ensure_kubeconfig!` into the `create_namespace` task. Also added one condition into this method, when the KUBECONFIG is unset and default path to config file does not exist, it raises the error. It looks like this:
![image](https://github.com/cnti-testcatalog/testsuite/assets/110407915/c5eb0bf5-fb79-4de6-b8f2-955ea6b2678d)

Also I write improvement ticket ( https://github.com/cnti-testcatalog/testsuite/issues/1968 ). There is 1 case when the test passes, but the k8s cluster is not up and running. Case occurs when KUBECONFIG is set successfully, indicating that the path to config file exists, but the file itself is empty or contains some faults, resulting k8s cluster is not running. So KUBECONFIG variable is set (the test passes), but the cluster is not running.

**Comment by lixuna** [comment]
ready for peer review, @taylor @HashNuke @agentpoyo
